### ISSUE TITLE
build fail at linking

### ISSUE THREAD

**Issue by davephillips** [michaelwillis/dragonfly-reverb#1]
Hi Michael,
I'm building on Fedora 23 Linux, GCC 5.3.1. Here's where it fails:

make[1]: Leaving directory '/home/dlphilp/src/dragonfly-reverb/dpf/dgl'
make all -C plugins/dragonfly-reverb
make[1]: Entering directory '/home/dlphilp/src/dragonfly-reverb/plugins/dragonfly-reverb'
g++ DragonflyReverbPlugin.cpp -Wall -Wextra -pipe -fPIC -DPIC -DNDEBUG -O2 -ffast-math -mtune=generic -msse -msse2 -fdata-sections -ffunction-sections -mfpmath=sse -fvisibility=hidden -DHAVE_JACK -DHAVE_LIBLO -std=c++0x -std=gnu++0x -fvisibility-inlines-hidden  -I. -I../../dpf/distrho -I../../dpf/dgl -I../../freeverb3 -MD -MP -c -o DragonflyReverbPlugin.cpp.o
mkdir -p ../../bin
g++ DragonflyReverbPlugin.cpp.o ../../dpf/distrho/DistrhoPluginMain.cpp -Wall -Wextra -pipe -fPIC -DPIC -DNDEBUG -O2 -ffast-math -mtune=generic -msse -msse2 -fdata-sections -ffunction-sections -mfpmath=sse -fvisibility=hidden -DHAVE_JACK -DHAVE_LIBLO -std=c++0x -std=gnu++0x -fvisibility-inlines-hidden  -I. -I../../dpf/distrho -I../../dpf/dgl -I../../freeverb3 -fdata-sections -ffunction-sections -Wl,--gc-sections -Wl,-O1 -Wl,--as-needed -Wl,--strip-all -Wl,--no-undefined   -ljack  -DDISTRHO_PLUGIN_TARGET_JACK -o ../../bin/DragonflyReverb
DragonflyReverbPlugin.cpp.o: In function `DISTRHO::DragonflyReverbPlugin::activate()':
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin8activateEv+0x12): undefined reference to `fv3::revbase_f::setSampleRate(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin8activateEv+0x2b): undefined reference to `fv3::revbase_f::setSampleRate(float)'
DragonflyReverbPlugin.cpp.o: In function `DISTRHO::DragonflyReverbPlugin::sampleRateChanged(double)':
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17sampleRateChangedEd+0x1e): undefined reference to `fv3::revbase_f::setSampleRate(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17sampleRateChangedEd+0x38): undefined reference to `fv3::revbase_f::setSampleRate(float)'
DragonflyReverbPlugin.cpp.o: In function `DISTRHO::DragonflyReverbPlugin::getParameterValue(unsigned int) const':
DragonflyReverbPlugin.cpp:(.text._ZNK7DISTRHO21DragonflyReverbPlugin17getParameterValueEj+0xd8): undefined reference to `fv3::zrev_f::getoutputlpf() const'
DragonflyReverbPlugin.cpp.o: In function `DISTRHO::DragonflyReverbPlugin::setParameterValue(unsigned int, float)':
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17setParameterValueEjf+0xfd): undefined reference to `fv3::revbase_f::setRSFactor(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17setParameterValueEjf+0x11a): undefined reference to `fv3::revbase_f::setRSFactor(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17setParameterValueEjf+0x192): undefined reference to `fv3::zrev2_f::setidiffusion1(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17setParameterValueEjf+0x1a2): undefined reference to `fv3::zrev_f::setapfeedback(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17setParameterValueEjf+0x1be): undefined reference to `fv3::earlyref_f::setoutputhpf(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17setParameterValueEjf+0x23f): undefined reference to `fv3::earlyref_f::setoutputlpf(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17setParameterValueEjf+0x63): undefined reference to `fv3::zrev2_f::setxover_high(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17setParameterValueEjf+0x83): undefined reference to `fv3::zrev2_f::setrt60_factor_high(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17setParameterValueEjf+0x13d): undefined reference to `fv3::zrev2_f::setrt60(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17setParameterValueEjf+0x15b): undefined reference to `fv3::revbase_f::setPreDelay(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17setParameterValueEjf+0x1d4): undefined reference to `fv3::zrev_f::setoutputhpf(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17setParameterValueEjf+0x203): undefined reference to `fv3::zrev2_f::setxover_low(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17setParameterValueEjf+0x223): undefined reference to `fv3::zrev2_f::setrt60_factor_low(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin17setParameterValueEjf+0x259): undefined reference to `fv3::zrev_f::setoutputlpf(float)'
DragonflyReverbPlugin.cpp.o: In function `fv3::zrev2_f::~zrev2_f()':
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD2Ev[_ZN3fv37zrev2_fD5Ev]+0x3): undefined reference to `vtable for fv3::zrev2_f'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD2Ev[_ZN3fv37zrev2_fD5Ev]+0x31): undefined reference to `fv3::comb_f::~comb_f()'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD2Ev[_ZN3fv37zrev2_fD5Ev]+0x3e): undefined reference to `fv3::comb_f::~comb_f()'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD2Ev[_ZN3fv37zrev2_fD5Ev]+0x58): undefined reference to `fv3::allpassm_f::~allpassm_f()'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD2Ev[_ZN3fv37zrev2_fD5Ev]+0x78): undefined reference to `fv3::allpassm_f::~allpassm_f()'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD2Ev[_ZN3fv37zrev2_fD5Ev]+0x84): undefined reference to `vtable for fv3::zrev_f'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD2Ev[_ZN3fv37zrev2_fD5Ev]+0xb0): undefined reference to `fv3::delaym_f::~delaym_f()'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD2Ev[_ZN3fv37zrev2_fD5Ev]+0xd0): undefined reference to `fv3::allpassm_f::~allpassm_f()'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD2Ev[_ZN3fv37zrev2_fD5Ev]+0xe1): undefined reference to `fv3::revbase_f::~revbase_f()'
DragonflyReverbPlugin.cpp.o: In function `fv3::zrev2_f::~zrev2_f()':
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD0Ev[_ZN3fv37zrev2_fD5Ev]+0x3): undefined reference to `vtable for fv3::zrev2_f'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD0Ev[_ZN3fv37zrev2_fD5Ev]+0x31): undefined reference to `fv3::comb_f::~comb_f()'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD0Ev[_ZN3fv37zrev2_fD5Ev]+0x3e): undefined reference to `fv3::comb_f::~comb_f()'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD0Ev[_ZN3fv37zrev2_fD5Ev]+0x58): undefined reference to `fv3::allpassm_f::~allpassm_f()'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD0Ev[_ZN3fv37zrev2_fD5Ev]+0x78): undefined reference to `fv3::allpassm_f::~allpassm_f()'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD0Ev[_ZN3fv37zrev2_fD5Ev]+0x84): undefined reference to `vtable for fv3::zrev_f'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD0Ev[_ZN3fv37zrev2_fD5Ev]+0xb0): undefined reference to `fv3::delaym_f::~delaym_f()'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD0Ev[_ZN3fv37zrev2_fD5Ev]+0xd0): undefined reference to `fv3::allpassm_f::~allpassm_f()'
DragonflyReverbPlugin.cpp:(.text._ZN3fv37zrev2_fD0Ev[_ZN3fv37zrev2_fD5Ev]+0xdd): undefined reference to `fv3::revbase_f::~revbase_f()'
DragonflyReverbPlugin.cpp.o: In function `DISTRHO::DragonflyReverbPlugin::DragonflyReverbPlugin()':
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0x2f): undefined reference to `fv3::earlyref_f::earlyref_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0x3e): undefined reference to `fv3::zrev2_f::zrev2_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0x4b): undefined reference to `fv3::earlyref_f::loadPresetReflection(long)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0x55): undefined reference to `fv3::revbase_f::setMuteOnChange(bool)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0x61): undefined reference to `fv3::revbase_f::setdryr(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0x6d): undefined reference to `fv3::revbase_f::setwet(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0x7d): undefined reference to `fv3::revbase_f::setwidth(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0x8d): undefined reference to `fv3::earlyref_f::setLRDelay(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0xa5): undefined reference to `fv3::earlyref_f::setLRCrossApFreq(float, float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0xbd): undefined reference to `fv3::earlyref_f::setDiffusionApFreq(float, float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0xd1): undefined reference to `fv3::revbase_f::setSampleRate(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0xe2): undefined reference to `fv3::revbase_f::setMuteOnChange(bool)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0xee): undefined reference to `fv3::revbase_f::setwet(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0xfa): undefined reference to `fv3::revbase_f::setdryr(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0x10a): undefined reference to `fv3::revbase_f::setwidth(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0x11e): undefined reference to `fv3::revbase_f::setSampleRate(float)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginC2Ev+0x175): undefined reference to `fv3::earlyref_f::~earlyref_f()'
DragonflyReverbPlugin.cpp.o: In function `DISTRHO::DragonflyReverbPlugin::~DragonflyReverbPlugin()':
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD2Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0x1f): undefined reference to `vtable for fv3::zrev2_f'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD2Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0x3f): undefined reference to `fv3::comb_f::~comb_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD2Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0x4c): undefined reference to `fv3::comb_f::~comb_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD2Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0x60): undefined reference to `fv3::allpassm_f::~allpassm_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD2Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0x80): undefined reference to `fv3::allpassm_f::~allpassm_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD2Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0x8c): undefined reference to `vtable for fv3::zrev_f'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD2Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0xc0): undefined reference to `fv3::delaym_f::~delaym_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD2Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0xe0): undefined reference to `fv3::allpassm_f::~allpassm_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD2Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0xf2): undefined reference to `fv3::revbase_f::~revbase_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD2Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0xfc): undefined reference to `fv3::earlyref_f::~earlyref_f()'
DragonflyReverbPlugin.cpp.o: In function `DISTRHO::DragonflyReverbPlugin::~DragonflyReverbPlugin()':
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD0Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0x1f): undefined reference to `vtable for fv3::zrev2_f'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD0Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0x3f): undefined reference to `fv3::comb_f::~comb_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD0Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0x4c): undefined reference to `fv3::comb_f::~comb_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD0Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0x60): undefined reference to `fv3::allpassm_f::~allpassm_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD0Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0x80): undefined reference to `fv3::allpassm_f::~allpassm_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD0Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0x8c): undefined reference to `vtable for fv3::zrev_f'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD0Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0xc0): undefined reference to `fv3::delaym_f::~delaym_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD0Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0xe0): undefined reference to `fv3::allpassm_f::~allpassm_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD0Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0xf2): undefined reference to `fv3::revbase_f::~revbase_f()'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPluginD0Ev[_ZN7DISTRHO21DragonflyReverbPluginD5Ev]+0xfc): undefined reference to `fv3::earlyref_f::~earlyref_f()'
DragonflyReverbPlugin.cpp.o: In function `DISTRHO::DragonflyReverbPlugin::run(float const**, float**, unsigned int)':
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin3runEPPKfPPfj+0xcd): undefined reference to `fv3::earlyref_f::processreplace(float*, float*, float*, float*, long)'
DragonflyReverbPlugin.cpp:(.text._ZN7DISTRHO21DragonflyReverbPlugin3runEPPKfPPfj+0x14a): undefined reference to `fv3::zrev2_f::processreplace(float*, float*, float*, float*, long)'
collect2: error: ld returned 1 exit status
../Makefile.mk:96: recipe for target '../../bin/DragonflyReverb' failed
make[1]: *** [../../bin/DragonflyReverb] Error 1
make[1]: Leaving directory '/home/dlphilp/src/dragonfly-reverb/plugins/dragonfly-reverb'
Makefile:20: recipe for target 'plugins' failed
make: *** [plugins] Error 2

**Comment by michaelwillis** [comment]
Fixed, the `Makefile` didn't include all of the necessary references to the compiled object files.
