### ISSUE TITLE
handling presets

### ISSUE THREAD

**Issue by rghvdberg** [michaelwillis/dragonfly-reverb#10]
The correct way to handle the presets is :
1) select preset in UI
2) UI informs Plugin a new preset is chosen 
3) Plugin set parameters
4) UI is informed the preset is loaded and updates the UI only (no setParamaterValue as we do now) 

The way we have it now *does* work but doesn't inform the Plugin a preset is changed.

**Comment by falkTX** [comment]
Yeah, this is the intention. but perhaps I forgot to handle it 100% in DPF.

**Comment by michaelwillis** [comment]
For now I removed the ability for the host to control the preset. We may find a better way to do this in the future.

**Comment by michaelwillis** [comment]
https://github.com/michaelwillis/dragonfly-reverb/commit/2f139c1a29376d64adaa12cc5f3d72eaa6f30d62
