### ISSUE TITLE
Latest crashes on Bitwig 3.2.7 (Mac)

### ISSUE THREAD

**Issue by carlca** [michaelwillis/dragonfly-reverb#102]
* macOS 10.14.6
* Bitwig 3.2.7

The latest build (4 Mar 2021 17:46) is crashing in Bitwig 3.2.7. Compared to others' reports in previous months, the situation has improved in that the plug-in actually loads and appears to be processing the sound. The problem starts when one tries to load the Dragonfly GUI. Bitwig crashes the plug-in, though thanks to Bitwig's sandboxing everything else is fine.

![Screenshot 2021-04-19 at 10 51 17](https://user-images.githubusercontent.com/260612/115217224-3158b800-a0fd-11eb-94ec-064da7be1d9a.png)

**Comment by michaelwillis** [comment]
What video hardware are you using? This might be a problem with Dragonfly Reverb's OpenGL dependency.

**Comment by carlca** [comment]
It's an old Mac Pro (early 2009) which has had the firmware flashed from 4,1, to 5,1 and had the patch ta https://dosdude1.com/mojave applied thus allowing my old "NVIDIA GeForce GT 120 512 MB" GPU to run macOS 10.14.6 Mojave. A handful of other plugins have similar problems, although ones intended for Metal GPUs tend to run just fine.

**Comment by michaelwillis** [comment]
@carlca Oh, I have had some other people with older macs report that the latest releases don't work for them. It seemed to start when I switched to using Catalina.

If you feel up to it, you can try building it for yourself. If I recall correctly, you need to install git and the xcode tools, then you can do this from the command line:
```
git clone --recurse-submodules https://github.com/michaelwillis/dragonfly-reverb.git
cd dragonfly-reverb
make
```

If all goes well, you should find the plugins in the `bin` directory.

**Comment by carlca** [comment]
Perfect! That worked a treat!! I have to say, your plugins are among the prettier on  my machine 😉

**Comment by michaelwillis** [comment]
@carlca Nice! I hope you have fun making some good music with these plugins.
