### ISSUE TITLE
Issue running VST in VCV HOST-FX

### ISSUE THREAD

**Issue by ContemporaryInsanity** [michaelwillis/dragonfly-reverb#104]
Running these VSTs in VCV RACK HOST-FX appears to work ok, until you dismiss the VST UI, which then causes the entire VCV RACK window to turn black, though the audio keeps working.  Similarly, swapping from one Dragonfly VST to another causes the same problem.

Pretty sure it's a Dragonfly issue as I've not seen this with any other VSTs in VCV RACK HOST-FX.

Current workaround is to minimise VST UI instead of closing and not switch to another VST once loaded.

No issues running same in Mixbus 6.

Running linux mint 18.1 xfce.

**Comment by michaelwillis** [comment]
This might be related to #73

**Comment by michaelwillis** [comment]
@ContemporaryInsanity Please try the new [release 3.2.6](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.6). This uses the latest version of [Distrho Plugin Framework](https://github.com/DISTRHO/DPF), which has some updates to the way that graphics are presented, and may fix this problem.

**Comment by ContemporaryInsanity** [comment]
Fixed.  Thank you!

**Comment by ContemporaryInsanity** [comment]
Having said that...

When running rack from terminal, dragonfly when running repeatedly prints the following:

assertion failure: "outparamsptr != nullptr" in file ../../dpf/distrho/src/DistrhoPluginVST3.cpp, line 2220

**Comment by falkTX** [comment]
Skip the VST3 version, prefer to load the VST2 for now.
VST3 within DPF is still experimental. Though that warning tells us that the host is misbehaving, not supporting parameter changes from the plugin side.

**Comment by falkTX** [comment]
the vst3 issues should all be fixed in 3.2.7 btw
