### ISSUE TITLE
plugin crashes my daws

### ISSUE THREAD

**Issue by TriYop** [michaelwillis/dragonfly-reverb#108]
When I add any of the Dragonfly reverbs (3.2.5, VST or LV2) to a track and open its interface, the DAW crashes with a common message on STDERR:

`assertion failure: "xWindow != 0" in file src/Window.cpp, line 288`

The message and behavior is the same on the following DAWS
- Reaper 6.29
- Ardour 6.6.0 
- Mixbus 6.2.407
- Muse 3.1.1

My system is running Linux  5.10.0-8-amd64 (debian 11)
on a AMD Ryzen 5 with a legacy behringer Xenix 1222 USB mixer as audio interface (48kHz).

**Comment by michaelwillis** [comment]
@TriYop What video hardware/driver are you using?

**Comment by TriYop** [comment]
I'm currently using NVidia's proprietary driver : 

    $> lspci | grep VGA
    07:00.0 VGA compatible controller: NVIDIA Corporation GK208B [GeForce GT 710] (rev a1)
    
    $>  cat /proc/driver/nvidia/version 
    NVRM version: NVIDIA UNIX x86_64 Kernel Module  460.91.03  Fri Jul  2 06:04:10 UTC 2021
    GCC version:  gcc version 10.2.1 20210110 (Debian 10.2.1-6) 

I am running Xorg 1.20.11 (12011000) on a dual screen with the following layout set on startup (don't know if this may help)

    xrandr --output HDMI-0 --below DVI-D-0

**Comment by michaelwillis** [comment]
> It used to work finely on the same hardware a few weeks ago (probably before update from debian 10.x to deian 11.0)

Oh, that's almost certainly related. Try building the latest and see what results you get:

```
git clone --recurse-submodules https://github.com/michaelwillis/dragonfly-reverb.git
sudo apt install libx11-dev libgl1-mesa-dev libjack-jackd2-dev
cd dragonfly-reverb
make
```

If that works, you'll find the plugins under the `bin` directory, copy them to some place that your DAW will find them, and see if it can load them.

**Comment by TriYop** [comment]
I deployed the lv2s to `~/.lv2/` after uninstalling the packaged instances (packages came from Librazik distribution)

Ardour crashed with a segmentation fault when loading plugin

I then started jack and tried the standalone version.

    $> ./DragonflyRoomReverb
    libjack.so.0 loaded successfully!
    [1]    55396 segmentation fault  ./DragonflyRoomReverb

on jackd I got the following message each time I launch an instance (sorry, it's in french), which seems to mean that plugins reaches at jackd.

    Changement du graphe des connexions JACK.

I then tried to add -ggdb flag to BUILD_CXX_FLAGS in order to run into gdb, but it seemed to have no effect.

    $> BUILD_CXX_FLAGS="-ggdb" make
    ...
    $> gdb ./bin/DragonflyRoomReverb
    GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
    ....
    Reading symbols from ./bin/DragonflyRoomReverb...
    (No debugging symbols found in ./bin/DragonflyRoomReverb)
    (gdb) run
    Starting program: /home/yvan/TMP/dragonfly-reverb/bin/DragonflyRoomReverb 
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    libjack.so.0 loaded successfully!
    [New Thread 0x7ffff6869700 (LWP 62552)]
    [New Thread 0x7ffff67e8700 (LWP 62553)]
    
    Thread 1 "DragonflyRoomRe" received signal SIGSEGV, Segmentation fault.
    0x000055555559d0b3 in ?? ()

**Comment by trebmuh** [comment]
> My system is running Linux 5.10.0-8-amd64 (debian 11)

and

> I deployed the lv2s to ~/.lv2/ after uninstalling the packaged instances (packages came from Librazik distribution)

LibraZiK-3 is made to work on top of Debian 10. Using LibraZiK package made for Debian 10 on a Debian 11 is a good recipe for a disaster. If you did that for a lot of packages, then your system is unstable and you'll be better to erase and reinstall something clean.

**Comment by TriYop** [comment]
@trebmuh thanks.
I  naively thought that dependancy management in the package manager would save me from those annoyments.  Let's clean the system and try again.

**Comment by TriYop** [comment]
- system cleaned with only debian  11 packages, 
- plugins rebuilt

WHen I launch with Jackd down :

    libjack.so.0 loaded successfully!
    Cannot connect to server socket err = Connection refused
    Cannot connect to server request channel
    jack server is not running or cannot be started
    JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
    JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
    JACK setup failed, using RtAudio instead
    [1]    80002 segmentation fault  ./DragonflyEarlyReflections

When I launch with jackd running 

    libjack.so.0 loaded successfully!
    [1]    80045 segmentation fault  ./DragonflyEarlyReflections

and still the same messages in jack console.

**Comment by falkTX** [comment]
build in debug mode using `make clean; make DEBUG=true` and then try the standalone in gdb.
Getting a trace will tell us where it is crashing.

**Comment by TriYop** [comment]
Thanks for the help on building it in debug mode. 
here is the gdb output

```
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bin/DragonflyRoomReverb...
(gdb) run
Starting program: /home/yvan/TMP/dragonfly-reverb/bin/DragonflyRoomReverb 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
libjack.so.0 loaded successfully!
[New Thread 0x7ffff6896700 (LWP 225507)]
Cannot connect to server socket err = Connection refused
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[Thread 0x7ffff6896700 (LWP 225507) exited]
[New Thread 0x7ffff6815700 (LWP 225508)]
[New Thread 0x7ffff6014700 (LWP 225509)]
[New Thread 0x7ffff5813700 (LWP 225510)]
JACK setup failed, using RtAudio instead

Thread 1 "DragonflyRoomRe" received signal SIGSEGV, Segmentation fault.
0x000055555561c07e in DGL::puglX11GlEnter (view=0x5555558e1be0) at src/pugl-upstream/src/x11_gl.c:116
116       glXMakeCurrent(view->impl->display, view->impl->win, surface->ctx);
(gdb) 
```
