### ISSUE TITLE
Run JACK stand-alone version headless

### ISSUE THREAD

**Issue by michaelwillis** [michaelwillis/dragonfly-reverb#109]
This task is to implement the ability to run the standalone binary without the user interface.

@falkTX Does DPF currently support a way of doing this? Also, is there a way to access command line parameters? I'm thinking of a way to allow a headless run to accept a preset as a command line parameter.

**Comment by falkTX** [comment]
Haha, the jack standalone is growing quickly in requested features. It was initially meant to be only for testing, but now even has RtAudio fallback in case JACK is not running (so it uses pulseaudio or alsa, etc)

You can already run headless, BUT it requires building the plugin with its GUI disabled.

For the command-line parameters, we can go 2 ways:
1. make a generic implementation on DPF that works for all plugins, allowing to set parameter MIDI-CC mapping, presets etc
2. allow plugins to handle argc/argv from main()

The 2nd option is quicker and gives more freedom, but is not as beneficial to the wider community.
Personally I would go for the 1st option, but I don't exactly have much time for this now, some other things take priority.

**Comment by michaelwillis** [comment]
@falkTX Even option #2 would work fine for me, I was just thinking of something easy like a `--dump` option that would write a textual configuration to stdout when the process exits, and then a `--setup` option that would accept the same textual format. Of course #1 could be really nice.

Maybe for running headless I could make a build that compiles another binary for each of the effects, named `DragonflyHallReverb-Headless`, etc.

**Comment by falkTX** [comment]
> @falkTX Even option 2 would work fine for me, I was just thinking of something easy like a `--dump` option that would write a textual configuration to stdout when the process exits, and then a `--setup` option that would accept the same textual format. Of course 1 could be really nice.

While that sounds quick in theory, we would need to come up with a parser and file format first.
And if going with a format, json is likely the best option. But then we need a json parser and writer...

It is not like it is a bad idea, but it really stretches the use of the standalone.
For what you describe tools like jalv can already do that.
And I also have something that will eventually be released as a tool to do all of these things, see https://github.com/falkTX/Chibi (basically a mini-host loader that supports saving and loading presets, built-in midi keyboard for synths, audio/midi device setup, etc etc all the usual goodies we can think of)


> Maybe for running headless I could make a build that compiles another binary for each of the effects, named `DragonflyHallReverb-Headless`, etc.

I can add a new makefile target for gui-less standalone stuff, but it is not very useful without the CLI arg parser.

**Comment by RussellAult** [comment]
Perhaps not quite what you're targetting, but (for what it's worth) being able to compile without a GUI is also one of the requirements for [building an LV2 plugin for the Elk platform](https://elk-audio.github.io/elk-docs/html/documents/building_plugins_for_elk.html).

**Comment by falkTX** [comment]
> Perhaps not quite what you're targetting, but (for what it's worth) being able to compile without a GUI is also one of the requirements for [building an LV2 plugin for the Elk platform](https://elk-audio.github.io/elk-docs/html/documents/building_plugins_for_elk.html).

You can already build without a GUI, that was never a problem

**Comment by RussellAult** [comment]
> You can already build without a GUI, that was never a problem

Ah, sorry, my bad.

**Comment by michaelwillis** [comment]
Maybe there's another way to do this - what if we develop a headless plugin host that can load any LV2 plugin without launching the GUI, and it can set all of the plugin parameters from the command line? Something like this:

`headless-horseman ~/.lv2/DragonflyHallReverb.lv2 -psize 32 -pwidth 90 -ppredelay 20 ...`

**Comment by falkTX** [comment]
> Maybe there's another way to do this - what if we develop a headless plugin host that can load any LV2 plugin without launching the GUI, and it can set all of the plugin parameters from the command line?

afaik jalv can already do this.

```
$ jalv.gtk3 -h
Usage:
  jalv.gtk3 [OPTION?] PLUGIN_URI - Run an LV2 plugin as a Jack application

...

Application Options:
...
  -l, --load=DIR             Load state from save directory
  -p, --preset=URI           Load state from preset
...
  -c, --control              Set control value (e.g. "vol=1.4")

```

**Comment by michaelwillis** [comment]
Oh wow, I wasn't familiar with jalv before this. Now I don't think there is any reason to add these features to the DPF Jack standalone.

I had somebody write me asking for a way to use dragonfly reverb on a Raspberry Pi without a display. I think jalv is a better solution than implementing more features in DPF.
