### ISSUE TITLE
Plugin crashes FL Studio while being closed

### ISSUE THREAD

**Issue by XGalaCtiX** [michaelwillis/dragonfly-reverb#113]
Plugin crashes FL Studio v20.8.4 (b.2072) running through Rosetta. It loads perfectly fine but it crashes my DAW while being closed.

My hardware:
Base model late 2020 m1 MacBook Air

**Comment by michaelwillis** [comment]
@XGalaCtiX Please try the new [release 3.2.6](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.6). This uses the latest version of [Distrho Plugin Framework](https://github.com/DISTRHO/DPF), which has some updates to the way that graphics are presented, and may fix this problem.
