### ISSUE TITLE
GUI does not load

### ISSUE THREAD

**Issue by tribenose** [michaelwillis/dragonfly-reverb#116]
I am encountering an issue where GUI is not being loaded for all variants of dragonfly reverb, for both LV2/VST, 32bit and 64bit. So far I couldn't find anyone with the same issue.

My PC specs:
AMD Ryzen 5 3400g with Radeon Vega Graphics
Windows 10 64bit

Dragonfly Reverb Version: v3.2.5 (have also tried v3.2.4)

DAWs tried: Reaper/Ardour

![image](https://user-images.githubusercontent.com/95115920/143668524-e4f4024a-77e1-4ba2-8f06-939939ae201c.png)

**Comment by michaelwillis** [comment]
@tribenose Please try the new [release 3.2.6](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.6). This uses the latest version of [Distrho Plugin Framework](https://github.com/DISTRHO/DPF), which has some updates to the way that graphics are presented, and may fix this problem.
