### ISSUE TITLE
Cannot select hall types when loaded to matlab

### ISSUE THREAD

**Issue by SeanZhang99** [michaelwillis/dragonfly-reverb#117]
When I was trying to load Early Reflect and Plate plugin into MATLAB R2021a using loadAudioPlugin function, I found the reverberation type (e.g. Reflection type in early reflection plugin) could be displayed and changed corrected (maybe. At least it shows up and could be changed by user). But when loading room and hall plugin, I cannot find correct property representing the room and hall types.
I wander whether these room types are just presets or they will effect the reverberation when I set all other parameters to the same?

**Comment by michaelwillis** [comment]
The room and hall types are just presets. Load these plugins in a DAW or other plugin host, select the room or hall that you want, and take note of all the dial settings. Then you can select the same when loading into MATLAB.
