### ISSUE TITLE
Builds broken for macos and win32 

### ISSUE THREAD

**Issue by michaelwillis** [michaelwillis/dragonfly-reverb#118]
@falkTX I recently fixed the plugin validation (there were a number of issues related to uninitialized variables), and updated the DPF dependency to its `develop` branch. The macos-universal and win32 jobs fail. Would you recommend waiting for the DPF support of VST3 to settle down, or could I dig into the build.yml file and try to fix these builds?

**Comment by falkTX** [comment]
the vst3 side is not worth having part of the default build just yet.
maybe a few more weeks, testing and feedback is welcome

the win32 builds being broken are due to github having a broken ubuntu base, old image worked fine and but new is borked.

**Comment by michaelwillis** [comment]
Fair enough, I'll update it to exclude the vst3 and use a different image for the win32 build.

**Comment by falkTX** [comment]
Feel free to grab https://github.com/DISTRHO/DPF/blob/develop/.github/workflows/example-plugins.yml and copy&paste, that one builds for all targets just fine

btw, for win32 the issue is only on ubuntu-20.04. the ubuntu-18.04 image is still fine.
