### ISSUE TITLE
Zita-Rev?

### ISSUE THREAD

**Issue by pschopen** [michaelwillis/dragonfly-reverb#121]
It appears that the algorithm behind dragonfly is also partly based on the zitarev algorithm which is simply amazing for classical production. Is there a way to disable the functionality that apart from zita was added to the hibiki algorithm that dragonfly is based on? Zita itself is very unhandy and dragonfly has a way better interface.

**Comment by michaelwillis** [comment]
Yes, turn modulation down to zero percent. Also for good measure, you can set spin and wander both to zero, although I think they have no effect if mod is zero.

**Comment by aktivde** [comment]
Thanks, that works quite well. However even after playing around to get it as close to my zita preset it still sounds slightly different. Do you know if Hibiki also modified the Zita algorithm?

**Comment by michaelwillis** [comment]
I haven't used Zita much, so I had to take a look at it to make a few more guesses:
* Turn the early level and early send to zero.
* Dial the width to 100%
* Low cut all the way down, high cut all the way up.

Ultimately, if Zita works for your use, why not just use Zita? Hibiki added quite a number of features to Zita, and Dragonfly isn't even the same as Hibiki. In particular, Dragonfly parametrizes the early reflection algorithm differently.

**Comment by aktivde** [comment]
Thanks for your efforts. I actually quite liked how dragonfly works and that I've got a few parameters more to play with. Especially modulation is interesting. Not adding much, just a little bit on top of zita.

Interesting, how the different algorithms relate to each other. Can I find more information about that anywhere? I also tried the freeverb3 reverbs once and totally failed setting them up...

**Comment by aktivde** [comment]
Just tried it out and it works amazingly well! Thank you so much. Now you can kind of start with zitarev and then build the early reflections step by step. This really an amazing reverb. Right now I try it against Phoenixverb and Lexicon, and it really can keep up. Totally on eye level.
