### ISSUE TITLE
Add IDEL (initial delay of the late reverb signal)

### ISSUE THREAD

**Issue by pschopen** [michaelwillis/dragonfly-reverb#122]
I just used dragonfly hall on a classical music project. It had to compete against lexicon, phoenixverb and Waves IR-1. I got really close to the result I wanted but I didn't manage to adjust the little time difference between dry signal and the start of the tail. The Tail startet slightly to late for my impression. However, I then made it back to freeverb3 hibiki and looked up if it was possible there. I copied my dragonfly settings to hibiki and looked further. And indeed: Hibiki has a knob called "IDEL" that is described as "The length of the initial delay of the late reverb wet signal in ms." – This was exactly what I was looking for. 

I know, that the main achievement of dragonfly was to make the amazing algorithms more accessible by decreasing possibilities. However, that seems to be quite import to modulate a proper concert hall. Maybe there could also be a more extended version of dragonfly or maybe something that includes all settings hibiki has?

**Comment by michaelwillis** [comment]
In Dragonfly Reverb, that parameter is called predelay. You can adjust it from 0 to 100 milliseconds.

**Comment by pschopen** [comment]
Oh, that does make sense. How did you decide which parameters dragonfly should contain compared to Hibiki?

**Comment by michaelwillis** [comment]
@pschopen I started out extremely minimalist, and then added parameters as people asked for them.

Some of the parameters have been combined. For example, the "High Cut" dial in Dragonfly Hall controls the low pass filter on both the early reflections and the late reverb.
