### ISSUE TITLE
Are there denormal issues with the reverb?

### ISSUE THREAD

**Issue by muziker** [michaelwillis/dragonfly-reverb#123]
I was testing out dragonfly reverb 3.2.5-33 hall - Great Hall in a 5th order ambisonic channel setup. There are 18 instances in a bus that has 36 channels of ambisonic audio in parallel as input. The original 2 channel stereo synth is fed into the iem multiencoder and eventually into a master with a decoder to binaural. The DAW is reaper on a linux with carla to view the cpu load at a buffer size of 512 and a sample rate of 48khz. There's one or two random glitches as i'm playing one track of bass through the iem encoder/decoder setup, but as soon as i stop playing the cpu load spikes from 0% at as the audio goes to zero to 80% cpu load. The reaper auto denormal per plugin is on.

**Comment by michaelwillis** [comment]
What operating system are you running? There have been occasional reports of this problem, but I haven't found anything conclusive. While the freeverb3 library makes a lot of effort to avoid denormals, it is possible that there are some places in the code that don't handle denormals properly.

I can't make any promises about fixing this, but I am working on a new minor release that fixes some issues with uninitialized values that might prevent the problem. Other than that, one person told me that his workaround is to put in a plugin that adds a very low decibel noise (like -50db) right before the reverb.

**Comment by muziker** [comment]
I've tried the low db noise method for something unrelated and that seemed to work. On the other hand i was reading somewhere that setting DAZ and FTZ in the code would help with this.

**Comment by michaelwillis** [comment]
[Release 3.2.10](https://github.com/michaelwillis/dragonfly-reverb/releases/download/3.2.10) has denormal protection that covers all of the DSP code.
