### ISSUE TITLE
[Feature Request] Ambisonic reverb

### ISSUE THREAD

**Issue by muziker** [michaelwillis/dragonfly-reverb#125]
How about development of an ambisonic style reverb? Supposedly the first channel, W, is the bass channel, but the rest can use the same reverb algorithm in mono, then diffusion matrixed into each other to give the final output channels. The wander/spin type cross modulation can happen across multiple outputs.

**Comment by vssasks** [comment]
I still use reverbassistant. No similar plugs so far. All are phasy like hell...

**Comment by michaelwillis** [comment]
The algorithms used in Dragonfly Reverb would have to be completely overhauled in order to support ambisonic features. This would be better done by forking the freeverb3 library and modifying it to create a whole new suite of reverb plugins that is specialized for ambisonics.

**Comment by muziker** [comment]
I'm not sure how anyone would do that algorithmically, since the fdn type reverbs are really approximations in a stereo environment. Ambisonic convolution reverbs on the other hand should work better, since it would probably mean converting existing impulses into the correct order, and applying convolution to specific channels.
