### ISSUE TITLE
HiDPI display

### ISSUE THREAD

**Issue by michaelwillis** [michaelwillis/dragonfly-reverb#134]
@falkTX I made a branch to experiment with HiDPI. The beginning of my UI constructor calls `getWindow().setGeometryConstraints(width, height, true, true, true);`, and I had to refactor some of my UI to proper SubWidgets in order for them to work with virtual coordinates instead of actual pixel offsets. While testing, I found that the VST2 and VST3 plugins seem to scale up properly on a HiDPI display, but the LV2 plugins still displays small. Is there something that I need to do to get the LV2 plugins to take the scaling hint?

Here's the branch: https://github.com/michaelwillis/dragonfly-reverb/tree/HiDPI

**Comment by falkTX** [comment]
Depends on the host I guess, not all support high-dpi.
But you should remove the initial `getWindow()`, the `TopLevelWidget` (which `UI` class is derived from) implements this already, and it might be needed for the plugin UI to work correctly.

**Comment by michaelwillis** [comment]
Yes, right now I'm trying to autoscale bitmap-based widgets. Eventually I should probably recreate all of the artwork at double scale, and then scale them down for Low DPI displays. My main question here is that the LV2 plugins seems to have different behavior than VST2 and VST3, and I'm wondering if I missed something in how I implemented the high DPI support.

**Comment by michaelwillis** [comment]
@falkTX I just noticed your first comment about calling `setGeometryConstraints` on the `TopLevelWidget`, I'll try that.

**Comment by falkTX** [comment]
Which hosts did you try?

**Comment by michaelwillis** [comment]
I tested on Ardour and Reaper

**Comment by michaelwillis** [comment]
@falkTX I tried removing `getWindow()` to call `setGeometryConstraints(...)` on the UI class itself. I still get the same behavior.

It's not really a big problem, for now I can direct people to avoid the LV2 plugins if they want High DPI support. I was mostly just wondering if I did something wrong.

**Comment by falkTX** [comment]
try with carla just to be sure, I know at least carla will pass the scale factor correctly

**Comment by michaelwillis** [comment]
@falkTX This morning I tested in Carla 2.4.3 with my display set to x2 High DPI. The VST3 plugin UI automatically scaled up x2, but the LV2 plugin UI displayed at 1x.

**Comment by falkTX** [comment]
I will try this later in the week, assuming I dont forget.
it is weird the LV2 doesnt set the scale, it is the format I use and test the most.

Can you try with the example dpf plugins? The "Info" one shows the host ui scale as text in the UI.
