### ISSUE TITLE
3.2.7: No source tarball

### ISSUE THREAD

**Issue by dvzrv** [michaelwillis/dragonfly-reverb#139]
Hi! Upon trying to update to 3.2.7 I noticed that there is no source tarball.

As this has happened multiple times before (https://github.com/michaelwillis/dragonfly-reverb/issues/50, https://github.com/michaelwillis/dragonfly-reverb/issues/76, https://github.com/michaelwillis/dragonfly-reverb/issues/128), I wonder why its creation can not be covered by the CI that already builds all the other artifacts.

**Comment by falkTX** [comment]
@michaelwillis can you do your usual steps for creating a source tarball? I need it as well for the kxstudio repositories.

**Comment by dvzrv** [comment]
Thanks!
