### ISSUE TITLE
Mac VST windows aren't sized correctly

### ISSUE THREAD

**Issue by Q-mii** [michaelwillis/dragonfly-reverb#143]
There's an awful lot of space on these plugin windows whenever I open them as VSTs in Element.
<img width="454" alt="Screen Shot 2022-11-02 at 12 08 41 PM" src="https://user-images.githubusercontent.com/77647979/199579861-fbf38dc0-4224-409b-b636-b1d7727a56ad.png">
<img width="688" alt="Screen Shot 2022-11-02 at 12 09 02 PM" src="https://user-images.githubusercontent.com/77647979/199579927-64189ab0-383c-479f-b7f3-d01913c56a41.png">
<img width="924" alt="Screen Shot 2022-11-02 at 12 10 10 PM" src="https://user-images.githubusercontent.com/77647979/199580095-27c7300c-d0ed-4cec-902b-30d2e4d68b0e.png">
<img width="926" alt="Screen Shot 2022-11-02 at 12 10 44 PM" src="https://user-images.githubusercontent.com/77647979/199580205-bfd41d0b-c0eb-45b4-ac2f-5c8f14505dff.png">

**Comment by michaelwillis** [comment]
@Q-mii Are you using the VST2 or VST3 plugins?

**Comment by Q-mii** [comment]
VST2. Though a redownload did fix it, thankfully. I wish there were audio components, though.From,KatieOn Dec 28, 2022, at 11:19 AM, Michael Willis ***@***.***> wrote:﻿
@Q-mii Are you using the VST2 or VST3 plugins?

**Comment by michaelwillis** [comment]
> I wish there were audio components, though.

Duly noted.
