### ISSUE TITLE
[Possible bug] 3.2.7 sometimes crashes after parameter interaction/saving/restoring

### ISSUE THREAD

**Issue by kiwijam** [michaelwillis/dragonfly-reverb#144]
I have quite a few Reaper projects using the Windows VST2 x64 dll of Dragonfly (Plate) and I've noticed that:

- Sometimes, trying to save an older project after changing parameters in 3.2.7 will crash Reaper.

- Sometimes, re-opening a project after successfully changing parameters in 3.2.7 will crash Reaper as soon as I try to access the plugin's UI. Or, if I get to the UI, will crash Reaper as soon as I attempt to change parameters. Reaper only stops crashing after manually (text editor) removing the plugin from the project.

- Sometimes, this also happens when adding a fresh instance of Plate to a new project.

Going back to 3.2.5 seems to fix the crashes.

**Comment by michaelwillis** [comment]
I don't have a way to test on Windows, and the VST2 plugins are becoming ancient history. I'm closing this issue with a recommendation to use CLAP, LV2, or VST3.
