### ISSUE TITLE
Changing to 0 predelay does nothing

### ISSUE THREAD

**Issue by falkTX** [michaelwillis/dragonfly-reverb#147]
Detected by @jesseverhage while checking differences in presets.
When we have a direct change from not-zero to zero predelay, the GUI updates but the plugin "engine" value does not, making it sound with the same predelay value as before.

**Comment by michaelwillis** [comment]
I was able to reproduce this in the room reverb by picking the `Small Vocal Room` preset which has zero predelay, turning up the predelay all the way, and then clicking the preset again. This is fixed in [Release 3.2.8](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.8)
