### ISSUE TITLE
3.2.8: No source tarball

### ISSUE THREAD

**Issue by dvzrv** [michaelwillis/dragonfly-reverb#150]
Hi! I'd like to package 3.2.8, but there is no source tarball.

**Comment by trebmuh** [comment]
https://github.com/michaelwillis/dragonfly-reverb/releases/download/3.2.8/dragonfly-reverb-3.2.8-source.tar.gz

**Comment by dvzrv** [comment]
okay....

The last one was of the form dragonfly-reverb-source-v3.2.7.tar.gz

Please stick with a naming scheme :cry:
