### ISSUE TITLE
Windows version contain a Trojan

### ISSUE THREAD

**Issue by joboschetti** [michaelwillis/dragonfly-reverb#154]
Hi, windows version is infecter.
contains a known trojan, not a false positive
![IMG_20230312_155147_898](https://user-images.githubusercontent.com/46676142/224552469-e447dbba-c5f3-4087-9f71-1440a2c535f0.jpg)

**Comment by falkTX** [comment]
100% false positive, antivirus are on a anti-mingw crusade lately. I suggest you find a better one.
