### ISSUE TITLE
3.2.9: No tarball

### ISSUE THREAD

**Issue by dvzrv** [michaelwillis/dragonfly-reverb#158]
Hi! There's no tarball for version 3.2.9

**Comment by falkTX** [comment]
the release was retracted

**Comment by michaelwillis** [comment]
The source tar file for 3.2.10 is here: [dragonfly-reverb-3.2.10-src.tar.xz ](https://github.com/michaelwillis/dragonfly-reverb/releases/download/3.2.10/dragonfly-reverb-3.2.10-src.tar.xz)
