### ISSUE TITLE
Plugins not being found in Bitwig Studio 5.0.11 MacOS

### ISSUE THREAD

**Issue by TheEpicRedstoner** [michaelwillis/dragonfly-reverb#164]
Currently in the process of switching from windows to mac on apple silicon and after using the universal installer Bitwig Studio can't find any of the plugins in any format, whereas on windows it works just fine. FL Studio does manage to find the plugins on mac so it might be a Bitwig issue. Any idea what could be causing this and how to fix it? Thanks in advance

**Comment by Declice** [comment]
Hello Same issues Here. I downloaded dragonfly-reverb-3.2.10-macos-universal.dmg then isntalled.
a folder in plugins has been created with vst files. but the cubase artist 13 does not identify it as vst. Not sure why.
any ideas how to solved this?
Macboock Air M1 
cubase artist 13
regards

**Comment by Declice** [comment]
FYI:
I Just downloaded [dragonfly-reverb-3.2.8-macos-universal.pkg] (prev version) and works fine...
Regards

**Comment by TheEpicRedstoner** [comment]
Forgot to reply but using version 3.2.8 fixed it. Thanks!
