### ISSUE TITLE
feature request: expose more parameters

### ISSUE THREAD

**Issue by magnetophon** [michaelwillis/dragonfly-reverb#18]
I read most of [the thread at linuxmusicians](https://www.linuxmusicians.com/viewtopic.php?f=48&t=17804#p87462), so I know you'd like to have as few parameters as possible.

That makes sense, but at the same time it can be usefull, fun, and a good learning experience to tweak all the parameters and hear what they do.

Would you consider having a tab-page with advanced settings?
That would bring the best of both worlds imho.

I'm particularly interested in all the parameters related to spin and wander.
In the above thread you asked what those are.
In case you haven't found the anser yet: these parameters can be found on some lexicon revers, where they modulate internal delay times and/or allpass-filters.
The more modulation, the smoother a reverb appears, but apparantly on some sources you can hear detuning that doesn't sound natural, hence the need to tweak these.
Note: I have never used a reverb withh these parameters, and I'm writing this from memory, so please take with a grain of salt.
Does the spin parameter sound anything like [this clip](https://drive.google.com/file/d/0B8pZ4pixAgbSNEpUZ3A0YUVuOUk/view)?
The first chord is without spin, then two chords with maximum spin and then one without again.
The clip was taken from [this thread](https://www.thegearpage.net/board/index.php?threads/lexicon-random-concert-hall-clips.1759521/page-2).

Afaik, there are no linux reverbs that allow for such modulation, so it would be cool if dragonfly-reverb would.

Thanks.

**Comment by michaelwillis** [comment]
@rghvdberg suggested that the GUI should stay simple, but more parameters can be exposed to the DAW. I'm curious, does Ardour support setting parameters the non-gui way when the plugin provides a GUI? I haven't found out how to open Ardour's fallback view when a plugin has a GUI.

**Comment by michaelwillis** [comment]
Answer from Ardour IRC:

> [11:11] &lt;ssj71&gt; MichaelWillis: yes, IIRC its in the context menu when you right click the plugin in the mixer view

**Comment by rghvdberg** [comment]
There's a drawback however.
When you want to automate a parameter then **all** parameters will be shown in the dropdown list. This kinda confusing maybe.
Only see 10 parameters in the GUI, but when automating , a gazillion appear :slightly_frowning_face:

**Comment by magnetophon** [comment]
@rghvdberg:
According to @michaelwillis this plugin [is not suitable for automation](https://github.com/michaelwillis/dragonfly-reverb/issues/17#issuecomment-374288884) anyway.

**Comment by rghvdberg** [comment]
Yeah, but users gonna do it anyway. And ~~bitch ~~ _complain_  about it. :smile:

**Comment by magnetophon** [comment]
@rghvdberg  Do you bring that up as a reason not to do it this way, or is that just an observation?

**Comment by rghvdberg** [comment]
Both I guess.
I'll have to check if you can create a parameter that is editable but not
automatable.
That would be a perfect solution.

**Comment by michaelwillis** [comment]
I would actually love it if I knew enough about the algorithms to hack Freeverb3 such that automation didn't cause that horrible noise. However, like we've discussed elsewhere, I think we need to make a proper v1.0 release before we try anything else. For now I think it is sufficient to expose more raw parameters to the DAW, and clearly document that this reverb is currently not suitable for automation.

**Comment by rghvdberg** [comment]
Done.

**Comment by magnetophon** [comment]
Great!  Thanks @michaelwillis and @rghvdberg.
@rghvdberg What do you mean by "Done"?  Did you already write the code, but not commit or push it?

**Comment by rghvdberg** [comment]
I meant,it's decided now.
Adding parameters is not that difficult I guess. Although I don't know
anything about the dsp.

**Comment by michaelwillis** [comment]
@rghvdberg I can make the change that exposes more parameters. Did you find out if there is a way to prevent the DAW from automating parameters? My guess is that there is no way to do that, but we can politely document that it is not recommended.

**Comment by rghvdberg** [comment]
oh my ..
this did the trick, comment out
      // parameter.hints      = kParameterIsAutomable;
plugin works otherwise, ui and generic ui work as aspected
no automation controls in DAW ...

**Comment by michaelwillis** [comment]
Wow, that's amazing, one of those many pieces of DPF that I probably saw and then forgot 😬

**Comment by rghvdberg** [comment]
also when wiggling the knobs in ui, no zipper noise
didn't test extensively ofc

**Comment by michaelwillis** [comment]
> also when wiggling the knobs in ui, no zipper noise

Hmm, it's possible that the noise was fixed by 9c3d0f96fed6d2eee813506b56624247d93884f6. Maybe it happened because the parameters were being updated while the DSP was actively processing samples.

**Comment by michaelwillis** [comment]
@magnetophon I haven't forgotten about this! I was busy implementing the spectrogram and fixing a variety of bugs that would crash the plugin host. I think I'll get to this in a bit, but it might be for a 1.1 release.

**Comment by magnetophon** [comment]
Great, I have patience.

**Comment by michaelwillis** [comment]
@magnetophon Thanks for the patience. The code has been updated to include `width`, `spin`, and `wander`: https://github.com/michaelwillis/dragonfly-reverb/commit/242be23d9c7784ff34744c41bb701bd20e9106ae

These are not included in the graphical interface, but I confirmed that at least Ardour can set them with the generic controls.

If you know how to compile it, please pull the latest and try it out. I will try to make a new release for all three platforms in the next few days.

**Comment by magnetophon** [comment]
Great, thanks!
I've compiled and ran it, but that is all I have time for right now, sorry.

**Comment by michaelwillis** [comment]
I forgot to mention that I also updated the presets so that they have different numbers for these parameters, based on presets from Hibiki Reverb.

**Comment by michaelwillis** [comment]
@magnetophon I just made an overhaul to the user interface such that it includes these new parameters. Some people are experiencing problems building and running the new release on some versions of Linux, but I will track those issues elsewhere. I'm closing this issue now that I have a solution that I am happy about.

**Comment by michaelwillis** [comment]
I forgot to mention, I have not yet updated the download links in the README.md visible on the github project page. Get the new version here: https://github.com/michaelwillis/dragonfly-reverb/releases/tag/0.9.2

**Comment by magnetophon** [comment]
Thanks! The new GUI looks great!

Unfortunately, I'm getting a compile error:
```
DragonflyReverbUI.cpp: At global scope:
DragonflyReverbUI.cpp:201:74: error: virt-specifiers in 'stateChanged' not allowed outside a class definition
 void DragonflyReverbUI::stateChanged(const char* key, const char* value) override
                                                                          ^~~~~~~~

```

Any ideas?

**Comment by trebmuh** [comment]
@magnetophon : https://github.com/michaelwillis/dragonfly-reverb/issues/27

**Comment by michaelwillis** [comment]
@magnetophon As referenced by @trebmuh, please pull the latest revision of the code and try again. My compiler only showed this as a warning instead of an error, but I have since fixed it in 0dce7599bc436d1740cb1f53bbaed4f3c0d40903.

**Comment by magnetophon** [comment]
Yes, that fixes it, thanks.
Could you do another release, or should I package a git version for my distro?

**Comment by michaelwillis** [comment]
@magnetophon I actually just replaced the files in https://github.com/michaelwillis/dragonfly-reverb/releases/tag/0.9.2

**Comment by magnetophon** [comment]
I'm getting the same error.

**Comment by michaelwillis** [comment]
@magnetophon Oh, sorry, the release is pinned to a specific revision. You should be able to build from the latest master. I'll make another release at some point, but I was hoping to do some code clean up first.

**Comment by magnetophon** [comment]
Yeah, as said: master works, but I'd like to update the package in my distro.

**Comment by michaelwillis** [comment]
@magnetophon I just released a minor update, please let me know if it works for you: https://github.com/michaelwillis/dragonfly-reverb/releases/tag/0.9.3

**Comment by magnetophon** [comment]
Thanks, works great.
I [upgraded](https://github.com/NixOS/nixpkgs/pull/48691) the NixOS pkg.
