### ISSUE TITLE
add license to about screen

### ISSUE THREAD

**Issue by magnetophon** [michaelwillis/dragonfly-reverb#22]
Currently it says: ``<insert licence here>``.

**Comment by michaelwillis** [comment]
Hahahaha, I kept meaning to get to this. Done now: https://github.com/michaelwillis/dragonfly-reverb/commit/52f2d9bfa0a49bd9730758ec9124f8c562c4d571

It will show up in the next release, or you can build from the master branch to see it sooner than that.

**Comment by magnetophon** [comment]
:)
