### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by rghvdberg** [michaelwillis/dragonfly-reverb#26]
https://github.com/michaelwillis/dragonfly-reverb/blob/75a7410f6ecae7f20f22e8bb3e59f5cfe02fc0b1/plugins/dragonfly-reverb/DragonflyReverbUI.cpp#L570

The name is Rob van **den** Berg
not dev ;-)

**Comment by michaelwillis** [comment]
Sorry about that, and that it took so long to get to it. I was in the middle of doing an update to the user interface. Fixed now.
