### ISSUE TITLE
current GIT master (=0.9.2) build failing in Debian Stretch

### ISSUE THREAD

**Issue by trebmuh** [michaelwillis/dragonfly-reverb#27]
Hi, I've tried compiling on a Debian Stretch from current git master which is the same at the time of writing than 0.9.2.

The build fails with:
... 
```
                                              ^
DragonflyReverbUI.cpp:64:108: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
 dKnob (this, this, &fNanoText, paramLowMult,   "%2.1f X",  knobx[3], knoby[2]);
                                                                              ^
DragonflyReverbUI.cpp: At global scope:
DragonflyReverbUI.cpp:201:74: error: virt-specifiers in ‘stateChanged’ not allowed outside a class definition
 id DragonflyReverbUI::stateChanged(const char* key, const char* value) override
                                                                        ^~~~~~~~
DragonflyReverbUI.cpp: In member function ‘virtual void DISTRHO::DragonflyReverbUI::onDisplay()’:
DragonflyReverbUI.cpp:346:9: warning: unused variable ‘xstart’ [-Wunused-variable]
   float xstart = 20.0f, ystart= 92.0f;
         ^~~~~~
```
...
Please, let me know if you need some more information.

**Comment by michaelwillis** [comment]
@trebmuh I fixed the problem with `override` this morning.

Which compiler version are you using? It worked for me, but admittedly I did get compiler warnings about conflating string literals and char*, so I will try to fix that soon.

**Comment by trebmuh** [comment]
Thanks for your quick answer.
Unfortunately, that's far beyond my skills (I'm not a coder at all), then I'll wait for your fix.
Please, feel free to ping me and I'll test it.

**Comment by michaelwillis** [comment]
@trebmuh Please try again, I hope it will work as of 8465d10

**Comment by trebmuh** [comment]
I'll try it and report back here in the few hours coming (need to finish some other stuffs first).

**Comment by trebmuh** [comment]
@michaelwillis just did it, and it compiles fine. Tested it a bit, and it does look to me that it's working as expected. Thank you for the quick fix!
Closing then.
