### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by michaelwillis** [michaelwillis/dragonfly-reverb#28]
@trebmuh I noticed at https://liberapay.com/trebmuh that you maintain a Debian package. What is required to get a package into the main Debian repo? It would be nice to distribute this reverb to a wider audience.

**Comment by trebmuh** [comment]
@michaelwillis sorry for the lag, I didn't noticed this message before and just stumbled across it while looking for documentation about dragonfly-reverb.

I'm not too sure about the process to get it included in Debian since I'm still learning the ropes there. I'll ask to the debian-multimedia-team and report back to you. I'm quite sure DF-R is already fulfilling the "needs to be maintained upstream" step. and I think you can certainly help with the process with clarifying the license used. It's written "GPL-3" on the README.md page, but the LICENSE file is a GPL-2 one.

**Comment by michaelwillis** [comment]
@trebmuh Thanks. Yes, I need to update the LICENSE file.

**Comment by trebmuh** [comment]
Ok, I've been replied and it looks like the path to get DF-reverb included in the next Debian (Buster) is fine for me to do it if you want/ask me to do it (I'm not sure if you're initial question here was about **you** getting it into Debian or if you were asking me to do it, please comment).

If that's about me doing it, I just need to install a Buster system and to make some modification to my actual (Stretch) package and to submit for pair-review to the multimedia-team. Not a big deal, and I needed anyway to install a Buster environment to dev on it for other stuff. This should happen sometime on the 10/15 following days, so this is a good timing anyway.

**Comment by michaelwillis** [comment]
Could you submit the package to the peer review team? I am not equipped to easily install Debian Buster right now. I will try to make the official 1.0.0 release very soon, I hope that I can fix a minor bug in the next few days.

**Comment by trebmuh** [comment]
Yes, I can do that. Will do in approximatively 10/15 days.
Feel free to ping me here if I didn't update this thread by then.

**Comment by michaelwillis** [comment]
Thanks! Let me see if I can cut the official 1.0.0 release by then.

**Comment by trebmuh** [comment]
@michaelwillis another thing which is needed for an official build is to provide a source tarball including the submodule (DPF) for the [release](https://github.com/michaelwillis/dragonfly-reverb/releases).

**Comment by michaelwillis** [comment]
Ok, I will include DPF in the tarball. I didn't realize that the tar.gz source download didn't include the git submodule.

**Comment by trebmuh** [comment]
@michaelwillis [the tar.gz source tarball of the 1.0.0 version](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/1.0.0) is still missing the DPF submodule.

**Comment by michaelwillis** [comment]
@trebmuh Hmm, github automatically generates the source archive, and it doesn't include the submodule. I'm not sure how to get it to do so, other than creating my own archive and uploading it as a release artifact.

**Comment by trebmuh** [comment]
> creating my own archive and uploading it as a release artifact.

I'm 99% sure that's the way other projects do.

**Comment by michaelwillis** [comment]
Ok, I uploaded a tar file with the source that includes the `dpf` submodule. I'm not sure if the Debian package maintainers expect a specific directory structure to be in the tar, so let me know if I need to adjust it.

https://github.com/michaelwillis/dragonfly-reverb/releases/download/1.0.0/DragonflyReverb-source-v1.0.0.tar.gz

Also, Github insists on the release page having the `Source code` download that does not include the submodule. I'm not sure if there is a way to remove it, but it would be nice if there were just some way to make that automatically include the dpf project. Oh well, that's not your problem to solve.

**Comment by trebmuh** [comment]
> Ok, I uploaded a tar file with the source that includes the dpf submodule.

Nice, all good now.

> I'm not sure if the Debian package maintainers expect a specific directory structure to be in the tar, so let me know if I need to adjust it.

It looks fine as it is now. I'll tell you if something is needed.

For github, I've got no idea, sorry. If something comes up to me, I'll let you know.

**Comment by michaelwillis** [comment]
@trebmuh These are pre-releases, I'm working on bug fixes. Once it stabilizes again, I will promote it to v1.2.0 as a stable release, and will include the source tar file.

**Comment by michaelwillis** [comment]
@trebmuh Nevermind... I just got feedback from my best tester, he wasn't able to reproduce any known bugs on v1.1.2, so I'm calling it an official release. I included the source code tgz:
https://github.com/michaelwillis/dragonfly-reverb/releases/download/1.1.2/DragonflyReverb-Source-v1.1.2.tgz

**Comment by trebmuh** [comment]
Hi @michaelwillis , just to let you know that I've been repackaging it for the future debian stable (aka "buster") and I've just uploaded it to [mentors.debian.net](https://mentors.debian.net/package/dragonfly-reverb) for peer-review while I'm looking for a sponsor for it.

In other words, _that's in the pipe_.

**Comment by michaelwillis** [comment]
@trebmuh Thanks! Which version is in the pipe? 1.1.2?

**Comment by trebmuh** [comment]
Yes.

**Comment by trebmuh** [comment]
Hi @michaelwillis , I'd need a contact email for you. Can you provide one please?

I'm on IRC #lad if you'd prefer not to write it here.

**Comment by trebmuh** [comment]
Oh, and I'd need a bit of an overall description as well (_a bit more than "A free hall-style reverb based on freeverb3 algorithms"_, think 4 or 5 lines of 80 characters which would be fine).

**Comment by michaelwillis** [comment]
How is this?

> Dragonfly Reverb is a hall-style reverb that uses Moorer's early reflection
> model and the allpass FDN Zita reverb algorithm. It is closely based on Hibiki
> Reverb from Freeverb3VST. It is available as LV2 and VST plugin formats, as well
> as a stand-alone JACK application.

**Comment by michaelwillis** [comment]
@rghvdberg Is it ok if we list you as an upstream contact on the Debian package?

**Comment by trebmuh** [comment]
@rghvdberg said he was fine with that on IRC.

@michaelwillis : I've used your nice definition as a base for the description on the Debian package. Thank you for this.

I've then uploaded a new package (including packaging improvements in regards with feedback from my previous try) for debian-multimedia maintainers peer-reviews.

_That's still, and progressing, in the pipe._

**Comment by dvzrv** [comment]
@michaelwillis as a general recommendation: Please keep the naming scheme and file type for source packages consistent! :)

**Comment by trebmuh** [comment]
@michaelwillis there is one question coming from the peer-review: why do you use an embedded libsamplerate instead of the system one?

My guestimate is that it's easier for cross-plateform building. If I'm right here, then could you please provide a configure detection or a configure option for using the system provided one?

**Comment by trebmuh** [comment]
@michaelwillis any news on this?

**Comment by michaelwillis** [comment]
@trebmuh Sorry, no update. This is a busy time of year, but I will try to get to this.

**Comment by trebmuh** [comment]
OK no worries, let me know when it's done.
Just so you know, Debian will soon enter its "freeze" time, meaning that no new package will be able to enter the repo for the futur stable. [See here](https://release.debian.org/buster/freeze_policy.html).
In other words, if we missed this deadline, DF-rev will have to wait for the next-next debian stable to get in the repo (>2 years).

**Comment by michaelwillis** [comment]
@trebmuh With the recent contribution by @jpcima, is there anything else that you need from me?

**Comment by trebmuh** [comment]
@michaelwillis would you make a 1.1.3 release with the current head master (which includes the patch from @jpcima ) ?
It would help me with the debian packaging.

**Comment by michaelwillis** [comment]
@trebmuh Done: https://github.com/michaelwillis/dragonfly-reverb/releases/tag/1.1.3

**Comment by trebmuh** [comment]
Hi @michaelwillis , just to let you know that I've been rebuilding a Debian package for 1.1.3 (with system libsamplerate as requested by debian peers), and sent it for review to [Debian mentors](https://mentors.debian.net/package/dragonfly-reverb).

**Comment by michaelwillis** [comment]
@trebmuh Thank you!

**Comment by trebmuh** [comment]
Hi @michaelwillis unfortunately I've been under a work-trip, then a flu (caught in the work trip!) and missed the deadline today.
What I can probably do is to provide you with stretch .deb package for the time being and then, keep working in the debian repositories for the next stable (in ~2/3 years probably).

**Comment by michaelwillis** [comment]
@trebmuh I hope you are getting better from the flu! Don't worry about missing the deadline; it would be nice to have this in Debian proper, but really anybody who wants to use it can easily download it from Github. Thanks for all of the support that you have been on this project!

**Comment by trebmuh** [comment]
Thank you for your nice words.

**Comment by reinerh** [comment]
@trebmuh Do you still have your source package somewhere? It seems to have been removed from mentors.d.n (probably because of inactivity).
Now that Buster has been released, it would be a good opportunity to get it into unstable.

**Comment by michaelwillis** [comment]
@reinerh: There is a source tar file available in the 2.0.0 release: https://github.com/michaelwillis/dragonfly-reverb/releases/tag/2.0.0

**Comment by reinerh** [comment]
@michaelwillis Thanks, but I was looking for the Debianization that @trebmuh already did. (It's no longer available at the mentioned location).

**Comment by jpcima** [comment]
@reinerh there is a debianization which @trebmuh made, although not exactly adapted from mainstream Debian. The one which has disappeared was most likely based on this one:
http://download.tuxfamily.org/librazik/decepas/pool/main/d/dragonfly-reverb/

Since @trebmuh is busy on a music tour and will be probably back shortly in august, you may find this useful if you can't wait.

It's not made fully in the Debian packaging norm, just be aware. (changelog not in english, as well as -librazik version scheme)

**Comment by trebmuh** [comment]
@reinerh The computer where I've made the one on mentor crashed a few weeks ago unfortunately. The closest Debian-ready package is the one on http://download.tuxfamily.org/librazik/decepas/pool/main/d/dragonfly-reverb/ now. It shouldn't a big deal to reach the Debian standards from it.

@reinerh are you a DD who would like to get it officially in the Debian repos?

**Comment by reinerh** [comment]
@trebmuh Okay, thanks. I'm only a DM, but also interested in getting it into the Debian repos.
Do you want to prepare it again and maintain it in Debian (I can probably find someone to upload it)? Or should I take it over?

**Comment by trebmuh** [comment]
@reinerh : feel free to take it over as long as you keep the notes in the package about my work. If you want/need me to translate what's in the d/changelog, please ask.

**Comment by trebmuh** [comment]
@michaelwillis : just to let you know that 3.1.1 is in LibraZiK-3 now (has been since the 11th to be precise).

@reinerh any news here?

**Comment by michaelwillis** [comment]
https://packages.debian.org/bookworm/dragonfly-reverb
