### ISSUE TITLE
tarball differs from git

### ISSUE THREAD

**Issue by magnetophon** [michaelwillis/dragonfly-reverb#29]
When I build from [the tarball](https://github.com/michaelwillis/dragonfly-reverb/archive/0.9.3.tar.gz)
I get:
```
make[1]: Leaving directory '/build/source/freeverb3'
make -C dpf/dgl
make[1]: *** dpf/dgl: No such file or directory.  Stop.
make: *** [Makefile:15: libs] Error 2
```

The ``0.9.3`` from git builds fine.

**Comment by magnetophon** [comment]
My bad, I just need to fetch the submodules.

**Comment by michaelwillis** [comment]
Yes, I've been meaning to make it more clear in the readme.
