### ISSUE TITLE
DragonFly reverb 's icon missing on dashboard

### ISSUE THREAD

**Issue by sub26nico** [michaelwillis/dragonfly-reverb#33]
Hello, with the standalone version of the 1.0.0 RC1 version, I haven't the dragonfly's icon 
on the dashboard on Librazik (based on Debian Stretch + MATE1.16.2).
![dragonfly icon](https://user-images.githubusercontent.com/23740642/47757090-12ec7100-dca5-11e8-8c88-4947e60f612b.png)

**Comment by jujudusud** [comment]
![capture du 2018-10-31 00-28-31](https://user-images.githubusercontent.com/12748768/47757360-4ed40600-dca6-11e8-9610-dce1186d39a3.png)

**Comment by michaelwillis** [comment]
@falkTX Does DPF have a way to bake an icon into the JACK app such that the OS can use it like this?

**Comment by falkTX** [comment]
It does not, and honestly I would not bother with it.
The standalone is just a quick way to test and debug the plugin.
I dont see it being very useful when the plugin already has ladspa, dssi, lv2 and vst versions - so it will work in pretty much all linux daws and hosts.

The window icon is really a minor triviality, no?

**Comment by sub26nico** [comment]
> The window icon is really a minor triviality, no?
I agree, and I report it here because I think @michaelwillis may want to know.
I mainly use dragonfly-reverb lv2 or vst in hosts, and the icon missing in the standalone is not a big problem version when I use it, imho.

**Comment by michaelwillis** [comment]
@sub26nico Thanks for reporting it. In a lot of cases, little bits of polish like this add up to make a big difference, so there is no harm is suggesting it. I think I'll take the advice of @falktx, since I don't know how to do this if the framework doesn't support it.
