### ISSUE TITLE
documentation ?

### ISSUE THREAD

**Issue by trebmuh** [michaelwillis/dragonfly-reverb#36]
I'm searching for documentation about the different controls button of the GUI. So far I've found #30 for Diffuse/Spin and Wander, but what about the other? I guess they are pretty standard, still I bet that a documentation page (wiki here, or a txt/pdf in the tarball) would be great for the first comers.

**Comment by michaelwillis** [comment]
@trebmuh Thanks for reporting this. I've had a technical writer approach me saying he is interested in writing a proper manual, hopefully it will be included in the next official release.

**Comment by trebmuh** [comment]
Super nice, thanks for letting me know.

**Comment by MaxPerl** [comment]
Dear Michael,
Thank you so much for your work. Dragonfly Reverb sounds really great and you are a real hero to bring such a wonderful reverb to Linux.
Nevertheless a detailed documentation would be really great, preferably in a tutorial style, where some uses of the reverb are explained in detail..
Best wishes and again thank you very much,
Max

**Comment by trebmuh** [comment]
@michaelwillis any news from the "technical writer" ?

**Comment by michaelwillis** [comment]
@trebmuh He sent me a rough draft months ago, but a lot has changed since then and I've been busy implementing Dragonfly Hall. Now that it's close to 2.0.0, I will begin editing the rough draft and work on putting up proper documentation somewhere public.

**Comment by trebmuh** [comment]
Nice to read! Thanks for your quick answer also.

**Comment by michaelwillis** [comment]
@trebmuh Here is the current draft: https://michaelwillis.github.io/dragonfly-reverb/dragonfly-hall-manual.html

It still needs some work, please review it and let me know if you have any suggestions.

I'll hopefully have a draft of the Dragonfly Room manual soon.

**Comment by trebmuh** [comment]
It looks very nice @michaelwillis .
Is it hosted somewhere then I can provide a PR for the little things (ie: typo) I see while reading?

**Comment by michaelwillis** [comment]
Yes, it is here in this same repo under the `docs` directory.

**Comment by trebmuh** [comment]
Thanks @michaelwillis . I've done a reading on it and it's a very nice documentation. I particularly like the examples you wrote on "how to hear-understand" the action of a dial. Very useful, thank you.

I made a PR here: #48 , hope that helps.

**Comment by michaelwillis** [comment]
@trebmuh Thanks! Pull requests are always welcome.

Dragonfly Room now has a manual here:
https://michaelwillis.github.io/dragonfly-reverb/dragonfly-room-manual.html

It is mostly a copy/paste of the Dragonfly Hall manual, please take a look and let me know if I missed anything.

**Comment by trebmuh** [comment]
@michaelwillis I had a read at it. Please, double-check the #53 PR I made before merging. HTH.

**Comment by michaelwillis** [comment]
@trebmuh Thanks! I reviewed and merged your pull request.

**Comment by trebmuh** [comment]
:+1:
