### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by 2Funky4u** [michaelwillis/dragonfly-reverb#41]
Dragonfly reverb requires GL >= 3.0 to show the graphical interface. Where do I get it?

**Comment by 2Funky4u** [comment]
not sure what this means

**Comment by rghvdberg** [comment]
sorry for the late repsonse
it basically mean that if the UI doesn't show up your graphics card is too old
GL (opengl) comes with the drivers of your graphics card

**Comment by 2Funky4u** [comment]
So it sounds like I'm SOL.

**Comment by trebmuh** [comment]
Alternatively, one can launch it using software openGL with the following command: `LIBGL_ALWAYS_SOFTWARE=1 DragonflyReverb`
