### ISSUE TITLE
Expose more parameters "under the hood"

### ISSUE THREAD

**Issue by michaelwillis** [michaelwillis/dragonfly-reverb#43]
Hibiki and ProG have several parameters that are not currently available in the dragonfly plugins. This task is to expose more of these parameters to the plugin host (but not on the GUI). Possible candidates:

**Dragonfly Hall**
* LFO 1
* LFO 2
* LFO Factor
* Spin Factor

**Dragonfly Room**
* Input LPF
* Output LPF
* Boost Bandwidth

**Comment by magnetophon** [comment]
I seem to remember reading in a forum that there is a dry/wet control for the spin/wander block, that is currently set to a fixed 30%.
That seems like a prime candidate for exposing.

An input/output output filter is also usefull, but can easily and more flexibly be done with an external plugin.
The dry/wet mentioned above is an internal thing, so  cannot be done with an external plugin.

**Comment by michaelwillis** [comment]
@magnetophon Yes, you are referring to what is called "Spin Factor" above, it is a percentage of how much the spin influences the signal. There should be a new release shortly that includes Spin Factor and LFO Factor.

**Comment by michaelwillis** [comment]
Resolved by 2f8abcc

**Comment by magnetophon** [comment]
@michaelwillis Thanks!

**Comment by michaelwillis** [comment]
@magnetophon You're very welcome, in case you haven't seen it, [Beta release 1.9.5](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/1.9.5-beta) includes this new feature.
