### ISSUE TITLE
Avoid running early or late algorithm if level is set to zero

### ISSUE THREAD

**Issue by michaelwillis** [michaelwillis/dragonfly-reverb#45]
Currently Dragonfly Hall and Dragonfly Room run both early and late algorithms, even if the early level or late level is set to zero. This task is to update the DSP code such that it avoids running an algorithm that will not impact the resulting sound.

**Comment by sub26nico** [comment]
Can it be related to #59 ?

**Comment by sp-pinkeye** [comment]
Currently testing a fix for this as I have same problems as in issue 59 in Mixbus/Ardour/Carla. Will post details after testing....

**Comment by michaelwillis** [comment]
@sp-pinkeye Great! Let me know how it goes!

**Comment by sp-pinkeye** [comment]
Attached the DSP.cpp from the Hall and Room with my changes ... have tested and seems to have sorted the problem when reopening projects in Mixbus/Ardour. Obviously would advise you thoroughly test !

[RoomDSP.zip](https://github.com/michaelwillis/dragonfly-reverb/files/4671620/RoomDSP.zip)

[HallDSP.zip](https://github.com/michaelwillis/dragonfly-reverb/files/4671617/HallDSP.zip)

**Comment by michaelwillis** [comment]
@sp-pinkeye Thanks! I edited your patch and put it up on a branch called [issue-45](https://github.com/michaelwillis/dragonfly-reverb/tree/issue-45). Hopefully I'll have a new release that includes this fix soon.

**Comment by michaelwillis** [comment]
@sp-pinkeye The new [release 3.1.1](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.1.1) includes your change. Please verify that it works for you.
