### ISSUE TITLE
Issues with DF Reverb 1.9.8-beta

### ISSUE THREAD

**Issue by sub26nico** [michaelwillis/dragonfly-reverb#46]
It seems there is a problem with this release on LibraZik distro.
LV2 and VST crashes the hosts (tried in Ardour and Reaper), the terminal said 'segment fault'. 
And the Jack application doesn't work.
I tried with the package from my distro and with the archive on the release page here.

**Comment by jpcima** [comment]
This is a backtrace. [DF-gdb.txt.gz](https://github.com/michaelwillis/dragonfly-reverb/files/3238012/DF-gdb.txt.gz)

The array `decayTimeString` seems too short by one element. (5 vs 6 accessed)

**Comment by michaelwillis** [comment]
@sub26nico confirmed, I get the same bug on Linux.
@jpcima Thanks for finding the bug! I only took a small look, but I was looking in the wrong place! I thought for sure that it was a bug in the spectrogram raster image renderer.
