### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by dbolton** [michaelwillis/dragonfly-reverb#49]
Any chance you could include a version number somewhere on the plugin (either on the files themselves or in the UI)?

I've found it difficult to know what version I'm on. At one point I had to use the browser download history (which gave a date) and match up with the release history in GitHub (which displays days since release). This was to help troubleshoot a problem that someone on Ardour IRC was having.

**Comment by michaelwillis** [comment]
@dbolton Click the question mark in the corner of the spectrogram display, it will show you the version. This feature has existed for quite a while, so even if you are using a very old version you should still be able to see the version.

**Comment by dbolton** [comment]
Thank you. I did not see that.
