### ISSUE TITLE
crash debug trace

### ISSUE THREAD

**Issue by davephillips** [michaelwillis/dragonfly-reverb#5]
Testing standalone with DEBUG=true. See https://pastebin.com/wg2zcbst for backtrace.

**Comment by michaelwillis** [comment]
@davephillips Thanks, I [committed a change](../commit/9c3d0f96fed6d2eee813506b56624247d93884f6) that might fix this, could you try again?

**Comment by davephillips** [comment]
Yes, I think that fixed the crash. I tested the standalone and the VST, both seem stable though I do still get the error "assertion failure: "font >= 0" in file src/NanoVG.cpp, line 829" from the standalone (possibly from the VST as well but I didn't start Bitwig from the command prompt). Also, there are some graphics problems that need to be fixed, as you can see in the attached screenshot.
![dragonfly-mw](https://user-images.githubusercontent.com/7815938/37187469-6f3d09fc-2318-11e8-8e6a-fea7900c8e8a.png)

**Comment by rghvdberg** [comment]
Ouch, your font's are rendered bigger than on my system :confused: 
This is kinda worrying.I'll have to investigate why that is. Maybe DPI settings from screen.
Are you using the Noto Sans font ?
Also I think the font should be in the source tree, but I was too stupid too stupid to figure out the relative path to the font.

The `assertion failure` is a warning from DPF that the height of the fader rectangle is of height 0.
I'm planning on re-facturing the faders either by making a new widget, or I could just _not_ draw the rectangle when the height < 1 pixel.
The faders now 'jump' to the position you click in the fader. I have no problem with that but for some people it is an 'unexpected behaviour.

**Comment by rghvdberg** [comment]
opened an issue for the text -> #6

**Comment by rghvdberg** [comment]
and #7 for the faders

**Comment by michaelwillis** [comment]
@davephillips Thanks for checking that! I'll close this issue as @rghvdberg has opened other ones for the graphical problems.
