### ISSUE TITLE
Source tarball missing in assets

### ISSUE THREAD

**Issue by dvzrv** [michaelwillis/dragonfly-reverb#50]
Heyo! I'm packaging dragonfly-reverb for Arch Linux and would like to build 2.0.0, but there's no source tarball in the assets, which provides the dpf directory.

Would you be interested in a script, that creates a source tarball for the assets for you?

**Comment by michaelwillis** [comment]
Sure, that script could be handy. I really wish that github would include submodules when it autogenerates the source tar file. Maybe I'll switch to including the source of DPF instead of referring to it with a submodule, then this problem would be solved for good.

**Comment by dvzrv** [comment]
Okay, meanwhile #51 should fix your problems!
Hope it behaves the way you require it

**Comment by dvzrv** [comment]
btw, not sure whether you use any CLI utilities for github, such as [hub](https://hub.github.com/), but that can potentially also be combined with that script quite well!

**Comment by dvzrv** [comment]
Closing, I would of course be very happy (from a packager standpoint), if you chose to create a detached PGP signature for your tarball(s) in the future! :)

**Comment by dvzrv** [comment]
@michaelwillis could you use the script to add the source tarball for version 2.0.0? :)

**Comment by michaelwillis** [comment]
@dvzrv I haven't ever used gpg, what considerations do I need to make in generating a key?

**Comment by michaelwillis** [comment]
@dvzrv I added the source tar to the 2.0.0 release, but I didn't create the gpg signature.

**Comment by dvzrv** [comment]
@michaelwillis thanks!

If you want to use gpg, but have never done so before, it's probably best to [read up on the topic](https://www.dewinter.com/gnupg_howto/english/GPGMiniHowto.html).
However, basically it boils down to creating a private/public keypair (you might know this terminology from SSH keys). The private key should be guarded by a password and only accessible by you, the public key should be uploaded to a keyserver (they sync between each other).

If  you're interested keysizes, and key algorithms, this is an okay writeup/overview: http://openpgp.vie-privee.org/pgpfaq.html
In my experience going for a 4096 bit RSA should be totally fine for your use-cases. If you feel, you're getting in trouble with various agencies, go for a bigger keysize of the elliptic curve type (e.g. 2048 DH) and avoid the internet ;-)

Thanks again, the initiative is very much appreciated!
