### ISSUE TITLE
How do I change the theme?

### ISSUE THREAD

**Issue by unfa** [michaelwillis/dragonfly-reverb#52]
I've seen the blue theme, and I want it! :D

**Comment by trebmuh** [comment]
@unfa why closing the issue then?

**Comment by michaelwillis** [comment]
@unfa The latest version has two plugins. The old plugin has been renamed `Dragonfly Hall Reverb` and is bundled with the new `Dragonfly Room Reverb`. The room reverb has the blue theme to visually distinguish it from the hall reverb, for people who use both.

Find the download link, upgrade instructions, and manuals here:
https://michaelwillis.github.io/dragonfly-reverb

P.S. It would be super awesome if you made a short video to showcase both of these plugins.

**Comment by unfa** [comment]
Sorry, I cloes this issue, when I realized that there's two plug-ins now.
I've already updated.

Actually I'm making a video about the Hall reverb plug-in :)
Later I'm probably going to cover the Room one also.

**Comment by michaelwillis** [comment]
@unfa Awesome! I look forward to seeing your videos.
