### ISSUE TITLE
SYSTEM_LIBSAMPLERATE=true fails with vendored freeverb3

### ISSUE THREAD

**Issue by dvzrv** [michaelwillis/dragonfly-reverb#56]
During build of 2.0.0 for Arch Linux I ran into the issue, that the vendored freeverb3 doesn't build when exporting `SYSTEM_LIBSAMPLERATE=true`.
To mitigate this issue I packaged freeverb3 and built against that instead, which worked.
I therefore devendored freeverb3 (optionally) with #55 and am now able to build with `SYSTEM_LIBSAMPLERATE=true SYSTEM_FREEVERB3=true make`, but `SYSTEM_LIBSAMPLERATE=true make` still fails.

**Comment by dvzrv** [comment]
Oh, and here is the build log for `SYSTEM_LIBSAMPLERATE=true make` (on current `HEAD`), with

* gcc 9.1.0
* libglvnd 1.1.1
* libx11 1.6.8
* jack 0.125.0
* glibc 2.29

[dragonfly-reverb-build.txt](https://github.com/michaelwillis/dragonfly-reverb/files/3356837/dragonfly-reverb-build.txt)

**Comment by michaelwillis** [comment]
@dvzrv Version 3.2.0 no longer has the libsamplerate dependency. Freeverb3 used libsamplerate to oversample, but Dragonfly Reverb doesn't use the oversample feature, it just had it set at x1. I modified the bundled Freeverb3 to remove the oversample feature, and then dropped the bundled libsamplerate.

Note that if you build with `SYSTEM_FREEVERB3=true`, you will still need the system libsamplerate dev library.
