### ISSUE TITLE
Please add unit to "size" knob

### ISSUE THREAD

**Issue by diovudau** [michaelwillis/dragonfly-reverb#58]
Size: 40 m
What m? radius of a round room ? square-meter m² ?  volume m³ ? Fourth-dimensional space-time? :)

**Comment by michaelwillis** [comment]
It isn't precisely a distance measurement, but consider it a one-dimensional depth of the room from front to back. If you want, you can kind of imagine `Width` being the side-to-side width of the room, expressed as a percentage of the `Size`.
