### ISSUE TITLE
Audio output problem when levels are set to 0

### ISSUE THREAD

**Issue by Spunge** [michaelwillis/dragonfly-reverb#59]
Dragonfly has a hard time with the levels being set to 0 after loading a session.

When setting all the early level, early send and late level controls of the dragonfly room reverb to 0, the plugin's audio output will not work as expected after a plugin host restart.

**Comment by michaelwillis** [comment]
I have never experienced this bug. What OS and plugin host are you using? Please describe what you mean by "not work as expected".

**Comment by Spunge** [comment]
I'm running Arch linux.

I've now discovered that this problem only occurs after loading the plugin / plugin host with these settings. *Not* when setting the parameters when the plugin is running (then it just doesn't output any reverb, as expected)

In synthpod, the audio is not output as long as dragonfly is receiving audio. If the input stops, the output will happen after a few seconds, resulting in a **lot** of sound from the speakers at once. Though i experienced this behaviour yesterday evening, i am unable to replicate this today.

In carla, the output is a distorted barage of sound when early & late send are at 0 when loading a session.
![image](https://user-images.githubusercontent.com/1842108/62005484-36f5b980-b134-11e9-9297-67031043fcb5.png)
![image](https://user-images.githubusercontent.com/1842108/62005476-2c3b2480-b134-11e9-9f9d-9ea6f5bb4bb7.png)
This i can replicate easily.

**Comment by michaelwillis** [comment]
@Spunge Are you using the LV2 or the VST plugin?

**Comment by Spunge** [comment]
i'm using the LV2 version of dragonfly room reverb from the arch repositories:
```
$> pacman -Qs dragonfly
local/dragonfly-reverb 2.0.0-2 (pro-audio lv2-plugins vst-plugins)
    A concert hall reverb and a room reverb
```

**Comment by michaelwillis** [comment]
@Spunge Please try the VST version and let me know if it exhibits the same bug. Also, are you using multiple instances of the plugin, or just one?

**Comment by Spunge** [comment]
The only VST host i've got on my system is Ardour. I'm unable to replicate this behaviour in Ardour regardless of using the VST or LV2 version of the dragonfly room reverb.

**Comment by michaelwillis** [comment]
@Spunge Carla also supports VST plugins.

**Comment by Spunge** [comment]
Oh wow, yeah, i seems Carla does not automatically scan vsts.

I'm not able to reproduce the issue in Carla. Not with VST, not with LV2. I've made a lot of changes to my system in the meantime regarding CPU / realtime settings.

Sorry, i think we can close this.

**Comment by sub26nico** [comment]
I have the same issue with lv2 DragonFly  Room Reverb plugin in Carla.
To reproduce : 
(JACK should be launched)
- Launch Carla
- Load “C* AmpVTS - Tube amp + Tone stack” plugin and connect it to system(capture_1)
- Load "LSP Compressor Mono”  and connect it to the “C* AmpVTS - Tube amp + Tone stack”'s output
- Load  “Dragonfly room reverb” and connect its inputs to LSP Compressor's output and DF Room's output to system(playback) 1 & 2
-Set “dry level” and/or “early level” at 0%. 
Save the Carla session, then quit. 
Re-launch Carla and load the session.  
No problem with DF Room vst plugin, only with the lv2.
I don't know if it the same bug, but I encounter this behaviour in Ardour or Mixbus with DF Room lv2. When re-opening a session, vu-meters goes to red with noise.

**Comment by michaelwillis** [comment]
The new [release 3.1.1](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.1.1) now avoids running the early or late algorithm if the corresponding level is set to zero.
