### ISSUE TITLE
Please include the license for all bundled components

### ISSUE THREAD

**Issue by zenvoid** [michaelwillis/dragonfly-reverb#62]
Some of the bundled software does not include their readme, authors, or license files. In order to comply with the licenses, they should be there. For example, the file common/kiss_fft/kiss_fft.c says: "SPDX-License-Identifier: BSD-3-Clause" and "See COPYING file for more information". But COPYING file is not there, and the BSD-3-Clause requires a verbatim copy of itself within the source: "Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer[...]". Same for bundled fonts Noto, Averia...

**Comment by michaelwillis** [comment]
Done: 8f0f89ed314b1ade3a5ca816fe085aa9114b088a

**Comment by zenvoid** [comment]
Perfect! Thank you very much for fixing this
