### ISSUE TITLE
Room reverb : width knob assigbed to wrong parameter ?

### ISSUE THREAD

**Issue by rghvdberg** [michaelwillis/dragonfly-reverb#63]
Got this via irc

> Found a bug in Dragonfly Room. The Width knob obviously is assigned to the wrong parameter - likely to size.
> Turning it instantly results in a huge size so that it becomes more of a delay than a room reverb.
>...
>knob assigned to the wrong parameter. It also shows meters instead of percent - unlike the hall reverb version.

**Comment by michaelwillis** [comment]
Thanks @rghvdberg. Do you know what version? I have been rearranging the code recently, which has resulted in major bugs in Room, but I haven't made any release.

**Comment by rghvdberg** [comment]
Seems the user used the git version. Let's close this.
Thanks
