### ISSUE TITLE
Can't see GUI

### ISSUE THREAD

**Issue by Flone-dnb** [michaelwillis/dragonfly-reverb#64]
I've just downloaded 3.0.0 and put downloaded folder to my VST plugins folder, opened it (DragonflyRoomReverb-vst.dll) in my DAW and I don't see any GUI.

What I'm I doing wrong?

P.S. When I was using 2.0.0 in other DAW earlier it worked but later it started to crash my DAW and not open. Here in LMMS 3.0.0 just don't have a GUI.

![Безымянный](https://user-images.githubusercontent.com/37961576/75619637-696f0580-5ba0-11ea-9dd9-8ae18f8afca9.jpg)

**Comment by michaelwillis** [comment]
Oh no! Are you using the 32 or 64 bit version? Have you successfully used previous releases? Try 3.0.0-RC2 to see if it works.

**Comment by Flone-dnb** [comment]
> Oh no! Are you using the 32 or 64 bit version? Have you successfully used previous releases? Try 3.0.0-RC2 to see if it works.

I updated my answer.

**Comment by Flone-dnb** [comment]
v3.0.0-RC2 - same problem - no GUI.

**Comment by michaelwillis** [comment]
Hmm, weird. What OS, CPU, and video card are you using? Which DAW were you using before? Are you able to get any audio from LMMS, even though the user interface doesn't work?

**Comment by Flone-dnb** [comment]
Windows 10 Home 64-bit. CPU: Intel i7-7700HQ, NVIDIA GeForce GTX 1060. I think it stopped working in Tracktion 7 (most likely) or Cakewalk. The plugin is blocking sound and if it's turned on I don't hear anything.

**Comment by Flone-dnb** [comment]
Just tried v3.1.2 and all working fine. Tried v3.0.0 again and it's also working fine. Seems like the problem was in my PC, not the program.

**Comment by michaelwillis** [comment]
@Flone-dnb Thanks for trying again, I'm glad it is working now.
