### ISSUE TITLE
Packaging for Ubuntu

### ISSUE THREAD

**Issue by eeickmeyer** [michaelwillis/dragonfly-reverb#66]
Hello! I'm the project leader for Ubuntu Studio, and while it's late to include dragonfly-reverb in the default installation of Ubuntu Studio 20.04 LTS, we at least want to have it available in the archive.

With that, I have packaged it for Ubuntu and it is undergoing review. The thing we're concerned is how you embedded NotoSans-Regular.ttf into a .cpp file, along with the .cpp file for the artwork. I'm assuming you used `xxd -i common/NotoSans/NotoSans-Regular.ttf` (for example), and same with the artwork.

The Ubuntu Archive Admins are skeptical if it's even allowed to embed (they might see it as a modification) NotoSans-Regular.ttf per the OFL, but if it can be explained how that is done via some documentation,, and that it's not truly a modification, that would be very helpful. Even responding to this issue so that I could link it to them would be helpful.

Thanks!

**Comment by michaelwillis** [comment]
Hi @eeickmeyer! I don't see it as modifying the font, it's just representing the font's binary data differently, as an array literal in C++ source code.

**Comment by eeickmeyer** [comment]
Thanks for the response, @michaelwillis. I agree, but some documentation (even in the root) as to how the file is created would be good. My assumption is you used xxd, but I need to know for certain. I don't see any problem with it personally, but the questions have been raised by people higher up than myself.

**Comment by rghvdberg** [comment]
IIRC I've created a header file with the xxd command.

**Comment by rghvdberg** [comment]
For Ubuntu we could easily set the noto font as a deb and load the file from disk.

**Comment by rghvdberg** [comment]
https://github.com/rghvdberg/dragonfly-reverb/commit/15977c05692463e8089c7be0bac39a9b5647c131
this seems to work.
Personally I don't _think_ we violate the license but just loading from disk is a safe and unambiguous way.

**Comment by michaelwillis** [comment]
The other way we could do it is to only distribute the ttf file, and wrangle the makefile such that it generates the source upon compiling the project. That way we're not distributing a different representation of the binary. Still, I think this is incredibly silly - this project in no way violates the spirit of the open font license, even if people want to quibble about the meaning of "Modified Version".

**Comment by eeickmeyer** [comment]
> Personally I don't think we violate the license but just loading from disk is a safe and unambiguous way.

I don't think so either, but I couldn't convince the archive admin reviewing it one way or the other.

> The other way we could do it is to only distribute the ttf file, and wrangle the makefile such that it generates the source upon compiling the project. That way we're not distributing a different 
representation of the binary.

I think this would be preferable. And yes, you're right, I think it's incredibly silly too. I guess it's just best to keep there from being any question. In my lintian checks, it never said that source contained a binary, so clearly lintian sees it as a valid source,

**Comment by eeickmeyer** [comment]
I hate to be the bearer of bad news, but I have a final rejection on this from the Ubuntu archive admins and numerous Debian developers. Unfortunately, this entire application is completely unredistributable (read: illegal in most countries). The SIL Open Font License is 100% incompatible with the GPL. Therefore, this cannot be distributed by Ubuntu, Debian, or any Linux distribution. Really, if the font is being compiled into the application (which it is), then both licenses are being violated. 

I highly suggest switching fonts to one that is not licensed under the SIL Open Font License. As it is, dragonfly-reverb should not, at least legally, be compiled anywhere until this is changed.

**Comment by rghvdberg** [comment]
Another font would require quite some work because of the font dimensions. Load from disk (and set the font as a dependency) is imho the logical conclusion here.

**Comment by michaelwillis** [comment]
@eeickmeyer Understood. I'm not sure when I'll be able to get to this. I don't currently know of an elegant cross-platform way to load the font from disk. I might be able to find a different font that is GPL and happens to have a similar layout.

**Comment by michaelwillis** [comment]
@eeickmeyer Please take a look at 72d53083c1318c4d3c725537417ea9285b45763c. From what I can tell, Bitstream Vera Sans is GPL compatible.

**Comment by eeickmeyer** [comment]
@michaelwillis Yes, Bitstream Vera Sans is 100% GPL compatible. I just confirmed with the Archive Admins.

**Comment by michaelwillis** [comment]
@eeickmeyer Thanks for checking. I'll hopefully make a new release soon, I have a few other odds and ends that I'm working on.

**Comment by michaelwillis** [comment]
@eeickmeyer Please try release 3.2.1, let me know if you have any trouble.

**Comment by eeickmeyer** [comment]
@michaelwillis 3.2.1 was just accepted into the Ubuntu archives. Welcome to Ubuntu and congratulations!
