### ISSUE TITLE
armv7l and aarch64 linux build

### ISSUE THREAD

**Issue by hexdump0815** [michaelwillis/dragonfly-reverb#67]
i just wanted to let you know that i successfully built dragonfly-reverb on armv7l and aarch64 (ubuntu 18.04) and it works well (tested on both platforms with reaper) ... here are the notes and the patch from my build try: https://github.com/hexdump0815/dragonfly-reverb-arm-build ... under releases one can find an example build

best wishes and keep up this cool project - hexdump

**Comment by michaelwillis** [comment]
@hexdump0815 Great work! I have only had vague thoughts about running on ARM. I can't make any promises about when or if I integrating this into the main project, but I'll see what I can do.

**Comment by hexdump0815** [comment]
@michaelwillis - thanks a lot for the info - that is nice to read
