### ISSUE TITLE
Plugin crashes in Ableton Live

### ISSUE THREAD

**Issue by gateraudio** [michaelwillis/dragonfly-reverb#69]
I'm using Ableton Live version 10.1.9, on a Windows 10 system, and the Dragonfly Reverb plugins worked fine when I first installed them (when there was just "Dragonfly Reverb" - the first version I downloaded was 1.1.2), however sometime around when I installed 1.1.3, the plugin stopped working completely. Now it loads for a while, showing no GUI (which seems to be similar to an issue other people have been having), and then crashes Live. Any effect racks I've made using the plugin will also cause Live to crash. This has persisted until the current version, regardless of which plugin I load in (even one of the new ones in version 3.0.0).

I've been using the 64-bit VST2 versions on a 64-bit computer, which has never changed, so I don't think that's the issue. I've tried uninstalling all versions, installing just the first version again, even checking the registry in case it's due to a registry key which hadn't been deleted, but nothing has been successful so far. 

I checked through Live's crash file, but there was nothing in the dump files I could decipher as to why the plugin crashed.
In case it helps, this is the last line in Live's crash log:
`2020-04-14T16:27:40.549469=device_add {"alg_latency":"0","buf_latency":"0","device_architecture":"Vst","device_name":"DragonflyPlateReverb-vst","device_type":"AudioFx","path":"DragonflyPlateReverb-vst","preset_name":""}`

**Comment by michaelwillis** [comment]
Hi @gateraudio, thanks for reporting this. Some other people using Win10 are also experiencing crashes like this. I can't promise anything right now, but I will see what I can do about this.

**Comment by gateraudio** [comment]
Thanks for looking into it (and for the quick reply!) - if you need a copy of the dump file I'd be happy to send it along, that might have more info than just the crash log.

**Comment by michaelwillis** [comment]
@gateraudio I don't know if this will help, but please try this version of Dragonfly Hall:

https://www.dropbox.com/s/ac39xrrylozdsf5/DragonflyReverb-Windows-64bit-v3.0.2.zip

This just removes the spectrogram display. In the past I've had a number of bugs related to to that feature; I'm wondering if it is high time to throw it out in the weeds.

**Comment by michaelwillis** [comment]
@gateraudio Oh yeah, and please do send me the dump. I don't know if I'll be able to make heads or tails of it, but it doesn't hurt to take a look.

**Comment by gateraudio** [comment]
Just tried the version without the spectrogram. Same issue again, it crashes, and personally I'm a big fan of that feature as well so I'd hate to see it go. Do you have an email I could send the dump file to? As I can't open it myself I'm wary of there being personal info inside so I'd rather not attach it here.

**Comment by michaelwillis** [comment]
@gateraudio Well, at least we're narrowing down the problem. My email address is my last name, then my first name at gmail.com, all lower case, no punctuation.

**Comment by michaelwillis** [comment]
@gateraudio  I think I found a new clue about what's causing the crash, somebody else reported issues related to OpenGL and their video hardware. Please run the command "dxdiag", select the display tab, and send me a screenshot.

https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe

Also, if you're willing, install the OpenGL Extensions Viewer and send me a screenshot of the summary tab:

https://www.realtech-vr.com/home/glview

**Comment by michaelwillis** [comment]
@gateraudio On a forum called [url=http://scoringcentral.mattiaswestlund.net/showthread.php?tid=600&pid=6162#pid6162]Scoring Central[/url], Chris Spyratos reported a bug that seems similar to yours. The dxdiag report that he sent me also had two displays: integrated intel graphics and nvidia, which is similar to your hardware. While trying to diagnose the problem, he found that the plugins do not crash if he uses the intel graphics. This isn't a complete solution, but please try it and let me know if it succeeds as a work-around for your problem.

I'm right now planning an overhaul to Dragonfly Reverb that should resolve this bug, but it is going to take me a while before I even have an alpha release of version 4 for you to try.

**Comment by Adri-7** [comment]
Thanks a lot ! I have the same issue and I can now manage to make your plugins work with Intel Graphics 😄

**Comment by gateraudio** [comment]
That'll be it then - I'm using a laptop with an nvidia graphics card which I set to do most of the work (seeing as it's the better one). After changing the setting back, it worked perfectly. Thanks!

**Comment by michaelwillis** [comment]
@gateraudio I'm glad that work-around helped you too. Hopefully I'll be able to drop the dependency on OpenGL one of these days, and then you can go back to using the nvidia hardware.

**Comment by michaelwillis** [comment]
@gateraudio I know this bug was reported forever ago, but the new [release 3.2.6](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.6) should fix this problem. There was a bug with how the plugins handled graphics that caused some plugin hosts to crash.

**Comment by retornz** [comment]
> @gateraudio I know this bug was reported forever ago, but the new [release 3.2.6](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.6) should fix this problem. There was a bug with how the plugins handled graphics that caused some plugin hosts to crash.

I own myself a MSI laptop with two video cards (Intel + NVidia), and I had the same issue with the v1.1.2, crashed LMMS when opening the UI...
Forcing the use of the Intel card fixed the issue. I tried your v3.2.6 and it works great with the NVidia card now ! No more crashes !

Great job for fixing this one & thanks for this great plugin, Keep it up !

**Comment by michaelwillis** [comment]
@retornz I'm glad the bug fix worked for you! Some of these issues have been really sneaky and hard to work on, because I only have so many combinations of hardware, OS, and DAW to test on.
