### ISSUE TITLE
Crashes FL Studio on Mac

### ISSUE THREAD

**Issue by foppas78** [michaelwillis/dragonfly-reverb#74]
Just installed the reverbs in the correct VST folder and FL crashes when I close the plugin or when I try to access the settings tab

**Comment by michaelwillis** [comment]
Please try the new release 3.1.2 and let me know if it crashes FL Studio.

**Comment by michaelwillis** [comment]
@foppas78 Have you tried one of the subsequent releases to see if this bug still happens? There is a new 3.2.3 release today which fixes a long-standing bug which might cause problems like this.
