### ISSUE TITLE
Plugin makes Reaper crash

### ISSUE THREAD

**Issue by Varnahir** [michaelwillis/dragonfly-reverb#75]
When I load the plugin in Reaper the application crashes. I use Reaper 6 64-bit on Windows 10.
The plugin that makes Reaper crash is also the 64-bit one. I tried using the 32-bit one instead and it simply did not work, but this time Reaper did not crash.
I have been using the Dragonfly Reberb plugins for sometime now without any problems. The last time I used it in a project was about four weeks ago. When I tried opening this last project, I noticed that the tracks that have the plugin applied sounded fine, the reverb is there. However, when I try to open the plugin floating menu to see or change the settings I get a black screen in the floating window for a few seconds and then the app shuts down.

Any suggestions? Thanks in advance.

**Comment by michaelwillis** [comment]
@Varnahir Please try the new release 3.1.2 and tell me if it crashes Reaper.

**Comment by Varnahir** [comment]
Hello and thanks for the response.

I tried the new version but the problem persists. Reaper keeps crashing.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Απαλλαγμένο
από ιούς. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Στις Κυρ, 28 Ιουν 2020 στις 12:07 π.μ., ο/η Michael Willis <
notifications@github.com> έγραψε:

**Comment by michaelwillis** [comment]
@Varnahir What video hardware do you have? A few people have reported a crash using nvidia GPU, but it works if they switch to the Intel GPU. If this works for you, it can be a way to work around the bug until I am able to fix the crashes.

**Comment by Varnahir** [comment]
I do indeed have an Nvidia GPU. I will try switching to the Intel one, if
this works. Thanks again for the input!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Απαλλαγμένο
από ιούς. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Στις Τετ, 1 Ιουλ 2020 στις 7:43 μ.μ., ο/η Michael Willis <
notifications@github.com> έγραψε:

**Comment by EtalonBeats** [comment]
I have a similar bug. In Reaper when I load only one of the dragonfly reverbs and I only display only one GUI it is okay, however, if I load multiple instances, and show multiple GUIs, then Reaper freezes, it doesn't crash, it simply freezes.
I have an NVIDIA GPU as well.

**Comment by michaelwillis** [comment]
@Varnahir @EtalonBeats The last couple of years have been crazy for everybody, but I'm back to working on this project. The new [release 3.2.6](https://github.com/Varnahir)https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.6) fixes some bugs with how to plugins manage the graphics context, and may address this issue. Please try it and let me know if you still experience this problem.
