### ISSUE TITLE
source tarball for 3.1.1 missing

### ISSUE THREAD

**Issue by dvzrv** [michaelwillis/dragonfly-reverb#76]
Hi! I'm packaging dragonfly-reverb for Arch Linux.
Currently I'm unable to package version 3.1.1, because the source tarball is missing.
[3.0.0 provides source assets](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.0.0) (which include the dpf directory). Without a source tarball that includes all your submodules I'm unable to build and package this software.

**Comment by trebmuh** [comment]
Workaround : `git clone ... --recursive && git checkout`. But I agree that a tarball is much better.

**Comment by dvzrv** [comment]
As I can not do any sort of source verification on a git repository (without signed tags or commits) this is not possible, as it would mean a downgrade from source tarball checksum verification to YOLO cloning from a tag and building that in the hopes that it will never change.

An alternative to custom source tarballs (at least in my case) would be to have PGP signed tags and commits.

@michaelwillis I have provided a script to gather all sources of a repository (including submodules) to a few upstreams. If you're interested I can create one for you in a pull request. That way you can create a source tarball asset based on a tag in this repository and upload it as a release asset.

**Comment by michaelwillis** [comment]
@dvzrv I keep forgetting to include the full source in the release. I do have a script to include it, I'll update release 3.1.1 soon.

**Comment by dvzrv** [comment]
Oh lol... I just realized you already have that in here! XD

Hm, maybe you can automate it in CI somehow? :)

**Comment by michaelwillis** [comment]
Yes, one of these days I should do proper CI, but I still haven't done it :bowtie:

**Comment by dvzrv** [comment]
@michaelwillis ping :)

**Comment by michaelwillis** [comment]
@dvzrv The 3.1.1 release has a bug regarding the dry level in the hall and room plugins. I'll fix that and make a new 3.1.2 release including the source tgz file.

**Comment by dvzrv** [comment]
Cool, works for me. Thanks! :)

**Comment by michaelwillis** [comment]
@dvzrv The source package is included in release 3.1.2.
