### ISSUE TITLE
Early Reflection hiccup (disconinuity)

### ISSUE THREAD

**Issue by x42** [michaelwillis/dragonfly-reverb#78]
https://github.com/michaelwillis/dragonfly-reverb/blob/bf4b55d5f96ff316109335d957a32bd05e0dc289/plugins/dragonfly-room-reverb/DSP.cpp#L116-L117

Since `early.processreplace` is only called conditionally this can lead to discontinuities.

early.processreplace() should probably be called unconditionally with a continuous stream of input data (to feed the FV3 internal delaylines).  Alternatively you could feed silence or, reset the early-delay DSP when `early_level == early_send == 0` for longer than the duration of the early reflections.

PS. late.processreplace() below has the same issue.

**Comment by michaelwillis** [comment]
This is resolved in release 3.2.1.
