### ISSUE TITLE
24khz hum that never dies in the Plate verb

### ISSUE THREAD

**Issue by naught101** [michaelwillis/dragonfly-reverb#79]
Most times I use the Dragonfly Plate Reverb, it leaves a strong super-high frequency hum at the tail of a verb. The hum appears to be at the sampling limit, e.g. 24khz on my machine. Obviously this is inaudible, but it's quite loud, and is likely to cause mixing problem.

Here's an example tail, recorded in bitwig:
![image](https://user-images.githubusercontent.com/167164/88479188-a04f1900-cf90-11ea-89e4-7c40907889e0.png)

The amplitude is NOT consistent, sometimes it's quite small, sometimes it's extremely loud (e.g. 0dB). Here are 3 bounces of the same thing, with no settings changes:

![image](https://user-images.githubusercontent.com/167164/88479231-00de5600-cf91-11ea-970b-a17065ae61f7.png)

They all sound similar, but the top one sounds a bit distorted.

These are my settings
![image](https://user-images.githubusercontent.com/167164/88479313-8cf07d80-cf91-11ea-9208-df24f4fab0f2.png)

Unfortunately, I am not really sure how to reproduce this. If I change the settings (e.g. set the dampen lower, and then set it back to 16kHz), it resets the noise, and then it doesn't always happen again. But if it happens once, the noise persists for ever, and builds up over time (every other time it happens it adds, I guess?). 

Let me know if there's any way I can provide more info.

**Comment by michaelwillis** [comment]
@naught101, so you are using 48kHz sample rate? Does this happen with either of the other reverb types (`nested` or `tank`), or does only the `simple` plate algorithm have this problem?

**Comment by naught101** [comment]
Yes, my audio interface us using 48kHz.

I thought I saw it on the Hall reverb as well, but it did happen when I tried again. I will try soon with the other Plate algorithms. Problem is that it only seems to happen now and then (e.g. every 15+ minutes? No idea really). But I can leave it on for a while and see what happens.

**Comment by michaelwillis** [comment]
Please download version 3.2.3 and observe whether the bug still happens:

https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.3

This new release fixes a long-standing bug in which sliders/dials set to zero could result in the plugins failing to initialize properly upon loading, which could cause all manner of havoc.
