### ISSUE TITLE
Install issue on Linux

### ISSUE THREAD

**Issue by danielagabti** [michaelwillis/dragonfly-reverb#82]
Hi there,

When I try to run make to build the files it returns the message "no rule to process the target 'dpf/Makefile.base.mk'". I'm using Kubuntu 20.04.
I've check dpf folder and it seems to be empty

**Comment by michaelwillis** [comment]
@danielagabti `dpf` is a git submodule. The easiest way I know of to get it is like so:
```
git clone --recursive https://github.com/michaelwillis/dragonfly-reverb.git
```

**Comment by danielagabti** [comment]
Thanks @michaelwillis 

It now runs make, with a lot of "linker input file unused because linking not done", but it completes make process and plugins are shown in Ardour plugin menu.

Anyway, it still crashing Ardour. I try this update because Ardour was crashing everytime I'm trying to put Dragonfly on a track. I'm using Ardour 5 (5.12.0) and it was working a month ago when I downloaded previous version of Dragonfly. Today I have to use it in a project and it crashes everytime. I didn't update Ardour since them. Maybe it's better to open another issue or you think it's an Ardour problem?

**Comment by michaelwillis** [comment]
@danielagabti Hmm, I don't immediately know why it would crash Ardour. It's working for me in Ardour 6.2, and I didn't have trouble in Ardour 5.12 either.

Does it crash immediately after adding the plugin, or when you try to open the GUI? Which specific plugin are you using? Do you have another plugin host that you can try, maybe Carla or something? Also, are you trying to use the LV2 or VST plugin? Maybe try the other one to see if it will work.

**Comment by danielagabti** [comment]
@michaelwillis yes, immediately after adding. I was using LV2, DragonFly Reverb Hall, but I try VST just for check and it crashes too. In Carla goes well, but it doesn't open GUI

**Comment by michaelwillis** [comment]
Did you build it using the `SYSTEM_FREEVERB3=true` environment variable? (If not, it compiles against the bundled freeverb library)

**Comment by danielagabti** [comment]
@michaelwillis no, I didn't. But I find out it was a problem with a nvidia driver update realized yesterday. When I was shutting down my PC the logout-greeter screen crashes and doesn't turn off. I search for this problem on internet and people are talking it was the driver update that requires a reboot to work (but it not ask me for reboot after updating). So, I reboot from terminal and test if it was that the cause dragonfly crashing and now it's working fine. I didn't imagine it could be for that. Until now, updates that requires reboot always asked for it. Sorry for the inconvenience.

Do you recommend for me build it again with freeverb library, anyway? If so, is there any link that explains how to do that?

Thank so much for the answers and congrats for the plugin, by the way. It has an amazing sound

**Comment by michaelwillis** [comment]
@danielagabti I'm glad you got it working! Don't worry about which freeverb library it is using, I was just trying to narrow down different possible problems. It seems like I have had similar problems related to video drivers in the past; I'm working on a Dragonfly Reverb 4 which will not depend on OpenGL and should prevent such bugs in the future.
