### ISSUE TITLE
Plugins vst not working

### ISSUE THREAD

**Issue by pedropoyart** [michaelwillis/dragonfly-reverb#90]
i tried using the vst plugin on a mac 10.13 with live 10.1.30 but the plugins do not show up.

**Comment by Sef319** [comment]
Same problem. Came here seeking wisdom, but I see that your query has not been answered yet. If you come across solution please share here. Many thanks.

**Comment by michaelwillis** [comment]
@pedropoyart @Sef319 Life was kind of crazy last year, but I'm getting back to working on this problem. There new [release 3.2.6](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.6), which includes a proper MacOS installer along with an update to the latest version of [Distrho Plugin Framework](https://github.com/DISTRHO/DPF). There have been several updates and bug fixes to DPF over the months, so the latest release may fix this problem.
