### ISSUE TITLE
3.2.3 Crashes Ableton Live 10 (Mac)

### ISSUE THREAD

**Issue by Rikstar23** [michaelwillis/dragonfly-reverb#93]
Just to let you know 3.2.3 vst crashes Ableton Live 10 when you open the vst in a track. Same for all four plugins.
MacOS 10.14.6
Live 10.1.3

**Comment by michaelwillis** [comment]
@Rikstar23 What video hardware do you have?

**Comment by Lachlan00** [comment]
Same for me with Mac OS 10.14.5 and Live 11.0.1. 

This was in the crash report
```
Dyld Error Message:
  Symbol not found: _objc_opt_new
  Referenced from: /Library/Audio/Plug-Ins/VST/DragonflyHallReverb.vst/Contents/MacOS/DragonflyHallReverb (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
```

Can send you the full report if that would be helpful?

**Comment by Rikstar23** [comment]
Hi Micheal,

Hardware:

Mac Pro: (early 2008)
Processor: 2 x 3.2 GHz Quad-Core Intel Xeon
Memory: 14 GB 667 MHz DDR2 FB-DIMM
Graphics: ATI RadeonHD 2600 XT 256 MB
macOS: 10.14.6

The older version of Dragonfly's have been working totally fine, so its not
a big issue. I have a feeling you may come back and say its to do with the
graphics card as this is starting to be an issue with some new updates of
other plugins.

Many thanks
Rik


Bhavatu sabba mangalam - May all beings be happy!

**Comment by Lachlan00** [comment]
Hi @Rikstar23, Would you mind sharing the most recent version that works on macOS 10.14.[X] for you?

**Comment by Rikstar23** [comment]
Hi @Lachlan,

I am finding Dragonfly 3.2.1 is very stable on macOS 14.10.6
I am currently using Live 11.0.

Bhavatu sabba mangalam - May all beings be happy!

**Comment by michaelwillis** [comment]
Oh, the latest release might be taking for you because I built it on MacOS 10.15. Depending on how comfortable you are with the terminal, you can try building it yourself. Either clone the repo or download the source package, and type `make` with no parameters. If the build succeeds you will find the plugins in the `bin` directory.

**Comment by Lachlan00** [comment]
Hi @michaelwillis, I ran the build on my end and 3.2.5 now works perfectly for me on macOS 10.14.5. Beautiful reverbs! Thanks for your help.

**Comment by michaelwillis** [comment]
@Lachlan00 That's good to know. Maybe I should find a way to build the official release against an older version of MacOS.

**Comment by Lachlan00** [comment]
That would be really useful. I know a lot of people (including myself) are holding back from upgrading past 10.14 as Apple ditched support for 32-bit applications and plugins from 10.15 onwards.

Looks like there are [a few ways you could do it](https://stackoverflow.com/questions/22362969/compile-a-c-program-from-terminal-using-gcc-for-older-os-x-version).

Now that I know how to do it, compiling new releases myself isn't really that much trouble. So you could also just provide instructions on how to compile for users with older systems?

**Comment by Koodikala** [comment]
Hi! I have the same issue on 10.14.6. I tried to build the plugin on my own (not a terminal wizard myself, but I think I did everything right) but I get this message: 

Makefile:7: dpf/Makefile.base.mk: No such file or directory
make: *** No rule to make target `dpf/Makefile.base.mk'.  Stop.

Any suggestion would be very welcome!

**Comment by michaelwillis** [comment]
@Koodikala This git repo uses a submodule for Distrho Plugin Framework. You need to either use the `--recurse-submodules` parameter when you first clone dragonfly-reverb, or you need to run the following from the project root directory: `git submodule update --init`.

**Comment by Koodikala** [comment]
Had some trouble properly cloning the repo (not so sure why, but it's totally on me). Tried again via github desktop and it worked no problem! Thanks for your support

**Comment by michaelwillis** [comment]
@Rikstar23 Do you still experience this issue on the latest [release 3.2.6](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.6)?
