### ISSUE TITLE
Hall's modulation on "0" isn't behaving quite right

### ISSUE THREAD

**Issue by JamesPeters667** [michaelwillis/dragonfly-reverb#97]
I tested both the Linux VST and LV2 versions of Hall in Reaper for this. 

I happened to be using a preset that actually had modulation on "0" (confirmed by using the non-GUI mode) and I noticed that the signal never entirely stopped being generated by Hall. The signal drops to below the hearing threshold, around -200 dBfs, but then it hovers there indefinitely. When raised loud enough it sounds like white noise.

Changing the modulation setting to even the smallest amount above "0" fixes this behavior.

If you're wondering how I noticed: I was testing a new insane compressor JS plugin (saike's Multiband Ravager), and I noticed some noise that never faded away.

The other Dragonfly plugins (Room, ER, Plate) don't have modulation, and I didn't notice this behavior with the same test.

**Comment by michaelwillis** [comment]
Oh weird! I'm assuming that you're using the latest release? I'll see if I can reproduce this.

**Comment by JamesPeters667** [comment]
Yes, 3.2.3. Sorry I should've mentioned that. With me anyway you can assume I'm using the latest if I report a bug. :)

It's going to require a spectrum analyzer capable of showing really far down into the noise floor. The Cockos Frequency Spectral Analyzer allows this (you can shift its range by dragging on the "floor" text). This is the kind of thing that would probably go unnoticed unless doing something really unusual in the mix, but I guess with sound design etc. anything is possible.

Be sure to send some signal through it first so it has something to generate sound.

**Comment by michaelwillis** [comment]
Give [version 3.2.4](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.4) a try.

**Comment by JamesPeters667** [comment]
That seems to have fixed it! Thanks!
