### ISSUE TITLE
Version 3.2.4 build with system freeverb3 broken

### ISSUE THREAD

**Issue by SpotlightKid** [michaelwillis/dragonfly-reverb#98]
The breaking commit seems to be 7657c26911abe82e9b30cdd812e3981ec8188bd3. `$PKG_CONFIG` needs to be in Makefile syntax, i.e. `$(PKG_CONFIG)` in all plugin Makefiles.

Otherwise you get linking errors: 

https://cpaste.org/?fb5dde810cc55fe6#2b6fPWXC9zZurQjCqtoNpHuyjvVD5Z62cjHWFPZFB942

**Comment by michaelwillis** [comment]
@snd1 ^

For what it's worth, I was able to build on Mac and Linux without any trouble. @SpotlightKid Which version of `make` are you using? If this isn't valid Makefile syntax, then I don't understand why it worked for me at all.

**Comment by michaelwillis** [comment]
@SpotlightKid Does cd8d2e83d40115857a79b2f528ea7f293b38cf68 fix this?

**Comment by SpotlightKid** [comment]
> don't understand why it worked for me at all.

Because those lines are only used when you compile with `SYSTEM_FREEVERB3="true"`.

Anyway, seems fixed now.

**Comment by snd1** [comment]
argh sorry forgot those brackets *facepalm*
